### ISSUE TITLE
Remove `critical-pod` annotation from Concierge and add `priorityClassName: system-cluster-critical` instead

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1090]
**Is your feature request related to a problem? Please describe.**

Concierge deployments cause this warning: `Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead.`

**Describe the solution you'd like**

Remove `critical-pod` annotation from Concierge and add `priorityClassName: system-cluster-critical` instead. See this old TODO in the code: https://github.com/vmware-tanzu/pinniped/blob/0651b9a91220bceec8e69c834e506b357dd750fb/deploy/concierge/deployment.yaml#L228-L230

**Describe alternatives you've considered**

None.

**Additional context**

Would this prevent deploys on Kube 1.16 and earlier? Would we be okay with that? We don't test against those old unsupported versions, so we're not sure if the Concierge deploys and works on those old versions anyway.

**Comment by joshuatcasey** [comment]
I think this was effectively done in #1693
