### ISSUE TITLE
[Proposal] Web UI for LDAP/AD login

### ISSUE THREAD

**Issue by margocrawf** [vmware-tanzu/pinniped#1113]
### Proposal Tracking Issue

- Proposal: https://github.com/vmware-tanzu/pinniped/pull/1116

- Discussion Links: 
    - https://kubernetes.slack.com/archives/C01BW364RJA/p1629723691160300
    - https://github.com/vmware-tanzu/pinniped/issues/882
    - https://github.com/vmware-tanzu/pinniped/issues/337
    - https://hackmd.io/@pinniped/Hk2WA1sb_#Possible-Future-Feature-Web-Based-LDAP-Login-Support

- Pull requests: 
    - https://github.com/vmware-tanzu/pinniped/pull/1163

**Comment by shamus** [comment]
There's already an issue for this work https://github.com/vmware-tanzu/pinniped/issues/1110 The design & implementation PRs can reference it.

I'm going to close this issue, please move the  content in the description to #1110

**Comment by cfryanr** [comment]
This feature was finished and released.
