### ISSUE TITLE
Audit logging support

### ISSUE THREAD

**Issue by shamus** [vmware-tanzu/pinniped#1124]
**Is your feature request related to a problem? Please describe.**

Audit logging is a requirement from most compliance standards (e.g. FedRAMP, PCI-DSS). Pinniped doesn't provide a way to meet these compliance requirements today. 

**Describe the solution you'd like**

Just like the API Server has capabilities to provide Audit logs for all API requests, Pinniped components should provide auditable log for events such as login attempts, access denied events, session creation, termination etc.

**Comment by joshuatcasey** [comment]
This is (mostly) done in #2009. Gaps in auditing should be indicated with future issues.
