### ISSUE TITLE
[Proposal] Dynamic Supervisor OIDC Clients

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1125]
### Proposal Tracking Issue

- Proposal: See PR #1126 

- Discussion Links: 
    - 
    - 

- Pull requests: 
    - https://github.com/vmware-tanzu/pinniped/pull/1181
    - https://github.com/vmware-tanzu/pinniped/pull/1255

**Comment by joshuatcasey** [comment]
This is complete.
