### ISSUE TITLE
Provide arm64 arch docker images

### ISSUE THREAD

**Issue by tiagomeireles** [vmware-tanzu/pinniped#1386]
**Is your feature request related to a problem? Please describe.**

I am unable to run pinniped on arm64 arch. Pinniped doesn't currently provide arm64 binaries and images. 

The images provided at `projects.registry.vmware.com/pinniped/pinniped-server` are single arch/platform.
```shell
$ docker buildx imagetools inspect projects.registry.vmware.com/pinniped/pinniped-server:v0.22.0
Name:      projects.registry.vmware.com/pinniped/pinniped-server:v0.22.0
MediaType: application/vnd.docker.distribution.manifest.v2+json
Digest:    sha256:481b94f4468425542f111143ebb69cd2057b0003e7bee75047892638cf88e135
```

**Describe the solution you'd like**

- Build and publish arm64 binaries.
- Build and publish multi-arch container images that includes arm64.

**Describe alternatives you've considered**

Building pinniped from source for arm64.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

Others are running on arm64. Approximately a year ago someone was getting pinniped to work on a rasphberry pi. [ref](https://kubernetes.slack.com/archives/C01BW364RJA/p1642548760039400?thread_ts=1640331346.191600&cid=C01BW364RJA)

**Comment by cfryanr** [comment]
Thanks for opening an issue @tiagomeireles!

Can you share more about your use case? Curious which platform you are using, which Kubernetes distribution, and what you're trying to accomplish.

Although we haven't tried this ourselves, it should be fairly easy to make a copy of the Dockerfile, adjust it for arm64 compilation flags, `docker build` the Dockerfile, push the resulting container image to your favorite registry, and then use that container image when deploying Pinniped. Curious if that works for you. If your client machine is also arm64, you could [compile the CLI](https://github.com/vmware-tanzu/pinniped/blob/main/CONTRIBUTING.md#building) with the appropriate arm64 flags too.

**Comment by thebearingedge** [comment]
I use an Ubuntu Linux VM on Apple silicon and do local cluster work in Docker (KinD/Talos/K3D). It would be really nice to be able to use matching images and cli. Happy to work on that!

**Comment by cfryanr** [comment]
Some thoughts on what we would need to change to support this for the *server*:
- [ ] Update build args and pod tolerations, see https://github.com/vmware-tanzu/pinniped/pull/1699
- [ ] Update CI to always build multi arch images
- [ ] Find a way to run the integration tests on an arm64 cluster, e.g. by creating an arm64 kind cluster in CI and running the tests there as a new CI job

Some thoughts on what we would need to change to support this for the *CLI*:
- [ ] Change CI to build windows, linux, and Darwin CLI binaries for arm64, in addition to the binaries that it already builds
- [ ] Change CI to attach these additional binaries to the GitHub release when creating a new release
- [ ] Check if we need to change how CI updates brew after each new release

**Comment by cfryanr** [comment]
The next release will include amd64+arm64 multi-arch container images for the server, and will also include arm64 for the linux/darwin/windows CLI. All the necessary changes have already been made, so we just need to create a release. 🎉
