### ISSUE TITLE
Pinniped installation on windows requires to use pinniped-cli-windows-amd64.exe version to check version, generate config etc. Can't use pinniped version as in MAC and Unix.

### ISSUE THREAD

**Issue by Naga15** [vmware-tanzu/pinniped#1412]
**What happened?**
Pinniped installation on windows requires to use "pinniped-cli-windows-amd64.exe version" (complete .exe file name)to check version, generate config etc. Can't use just "pinniped version" as in MAC and Unix

> Please be specific and include screenshots and logs!
![image](https://user-images.githubusercontent.com/15844219/217738824-58ff0e5c-0e4d-4dd8-8414-db52a3d41531.png)

![image](https://user-images.githubusercontent.com/15844219/217739629-3dc4be05-21ce-40f2-bcee-7d1c28319a0c.png)

**What did you expect to happen?**
pinniped version should simply work on windows just lke in MAC, Unix and also browsers and windows don't trust Pinniped cli installation as they see this coming from an unknown publisher and unsafe. The reason to mention this cause it's being blocked in Corporate laptops machines.

> Please be specific and include proposed behavior!
typing pinniped on command prompt should be recognized and output cli options.
 
**What is the simplest way to reproduce this behavior?**
Install windows pinniped-cli-windows-amd64.exe on a windows machine and try the commands as mentioned in the screenshot
 
**In what environment did you see this bug?**
- Pinniped client version:
- this is the link from where i installed cli version i installed (https://get.pinniped.dev/v0.22.0/pinniped-cli-windows-amd64.exe)

**What else is there to know about this bug?**
above should be enough.

**Comment by joshuatcasey** [comment]
Hi @Naga15 thanks for opening the issue. If you download the Windows CLI binary from one of the releases then the filename will be `pinniped-cli-windows-amd64.exe`. To shorten the filename to `pinniped` to match all of the examples, you can just rename the file or create a symlink called `pinniped` to that file.

**Comment by joshuatcasey** [comment]
I'm curious to hear about how you are using Pinniped - please let us know in a comment here. 

I'll close this issue for now since we plan to keep the binaries attached to the release named the same. Let us know if renaming or symlink does not work.

**Comment by cfryanr** [comment]
@Naga15 Some clarifying questions:
1. Are you able to download the binary? If your browser is blocking it, did you try using something like `curl` or `wget`? From the command prompt screenshot, it seems like you were able to download it somehow.
2. Are you able to execute the binary, or is a Windows security feature blocking you from running it? What did you mean by "The reason to mention this cause it's being blocked in Corporate laptops machines"? From the command prompt screenshot, it seems like you are able to run it.

**Comment by Naga15** [comment]
> I'm curious to hear about how you are using Pinniped - please let us know in a comment here.
> 
> I'll close this issue for now since we plan to keep the binaries attached to the release named the same. Let us know if renaming or symlink does not work.

I tried symlink using below command
mklink /H pnniped-cli-windows-amd64.exe pinniped which is not working .. tried renaming it by running
ren pinniped-cli-windows-amd64.exe pinniped is not working but renaming it to pinniped.exe is working.

**Comment by Naga15** [comment]
> @Naga15 Some clarifying questions:
> 
> 1. Are you able to download the binary? If your browser is blocking it, did you try using something like `curl` or `wget`? From the command prompt screenshot, it seems like you were able to download it somehow.
> 2. Are you able to execute the binary, or is a Windows security feature blocking you from running it? What did you mean by "The reason to mention this cause it's being blocked in Corporate laptops machines"? From the command prompt screenshot, it seems like you are able to run it.

I'm able to download it (in company laptop as well)... the screenshot provided is from my personal laptop. My concern is browser don't deem it safe but i think it's ok. I can manually mark is safe and keep it. @cfryanr

**Comment by cfryanr** [comment]
Thanks for sharing that information @Naga15. It sounds like you are able to successfully download and use the CLI binary, and that you've found it to be more convenient to rename the binary to `pinniped.exe`. That seems like a good resolution for this issue for now.

We're not planning on investigating how to sign the binaries at this time. Please let us know if you have any concerns.

PS - By the way, another option to install the CLI would be to download the Go compiler and compile the binary on your machine from source. Just mentioning that in case it might be helpful to other people in the community reading this thread.
