### ISSUE TITLE
Allow specifying the various display names when getting a kubeconfig

### ISSUE THREAD

**Issue by voor** [vmware-tanzu/pinniped#1424]
**Is your feature request related to a problem? Please describe.**

`pinniped get kubeconfig` is great, it's convenient, it's a fantastic way when you already have pinniped on your cluster and you just quickly want to hand off the kubeconfig to somebody.  It's straightforward and does what it's supposed to.  The only thing that's a little confusing is that I'm not entirely sure where the users name, the cluster name, and the context name comes from.

**Describe the solution you'd like**

We already have:
```
      --generated-name-suffix string             Suffix to append to generated cluster, context, user kubeconfig entries (default "-pinniped")
```

Just suggesting we add:
```
--generated-name-server
--generated-name-context
--generated-name-user
```

This allows overriding everything.

**Describe alternatives you've considered**

Since I have many clusters using pinniped, I've considered that this would not solve for generating a "super config" that contains all of my pinniped clusters and appropriately naming all of them.  I would probably consider that a better feature than this, but just wanted to capture this idea since it's probably more direct.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by cfryanr** [comment]
Any thoughts about the above info @voor?

**Comment by voor** [comment]
Yeah, I think what I'm looking to accomplish is something to achieve generating all of those kubeconfigs from multiple clusters without jumping to each individual one, that might actually be something better achieved on the management cluster (using Cluster API), since the information to generate those pinniped-ready kubeconfigs lives there.
