### ISSUE TITLE
Change path to `pinniped` CLI binary in kubeconfig files generated by `pinniped get kubeconfig`

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1451]
**Is your feature request related to a problem? Please describe.**

`pinniped get kubeconfig` puts the full path to the CLI binary that was used to invoke `pinniped get kubeconfig` into the generated kubeconfig.

The problem with putting the full path into the generated kubeconfig is that the operator generates the kubeconfig on their own machine, but then hands that file to end users to use on their own machines which probably have pinniped installed in other locations. This is especially bad when mixing and matching Linux and Windows machines in this worklflow, because a path like `/usr/local/bin/pinniped` won't work on Windows.

**Describe the solution you'd like**

We might want to just put the name of the executable that was used to invoke `pinniped get kubeconfig` into the generated kubeconfig, without putting the full path to the executable. This would be an improvement, but would still assume that all users of that kubeconfig file are going to name the Pinniped CLI binary the same (e.g. `pinniped`).

We might want to add a new CLI flag to pinniped get kubeconfig to allow the operator to choose (or at least influence) what path to the pinniped CLI is put into the kubeconfig file. For example, the admin might distribute the pinniped CLI binary as a different name (e.g. `acme-corp-auth-plugin`), or on some standardized path where they expect the binary to be installed across all end user machines (e.g. `/usr/acme-corp/bin/pinniped`).

**Additional context**

Would having `pinniped` as the path in the kubeconfig file on Windows find an executable called `pinniped.exe` in the user's path? One user reported that this works, while another user said that it didn't. We should try it.

**Comment by benjaminapetersen** [comment]
Would it make sense to provide options to:
- Generate kubeconfig file for linux (and use most likely path/binary name)
- Generate kubeconfig file for macos (and use most likely path/binary name)
- Generate kubeconfig file for windows (and use most likely path/binary name)

At least for defaults, but perhaps provide flags or some way to override these?

**Comment by Zeratoxx** [comment]
> Would having pinniped as the path in the kubeconfig file on Windows find an executable called pinniped.exe in the user's path? One user reported that this works, while another user said that it didn't. We should try it.

On Windows and Linux there is a PATH variable that is used exactly for this case. I don't know how this is handled on MacOS, but I imagine there is a PATH variable there too.

So yes, this should work afaik.
