### ISSUE TITLE
Supervisor goes into crashloopbackoff if kapp using --into-ns flag for Pinniped 0.20+

### ISSUE THREAD

**Issue by laidbackware** [vmware-tanzu/pinniped#1455]
**What happened?**

When deploying 0.20+ into a cluster using kapp controller, the deployment succeeds when the target namespace is NOT overridden, but when the `--into-ns` flag is used during `kapp deploy` the supervisor pods fail to start. Version 0.19 and prior are not affected.

> Please be specific and include screenshots and logs!

**What did you expect to happen?**

Expect the kapp deployment to complete regardless of the target namespace.

**What is the simplest way to reproduce this behavior?**

This works:
```
kapp deploy -y --app pinniped-supervisor --file https://get.pinniped.dev/v0.22.0/install-pinniped-supervisor.yaml
```

This does not:
```
kubectl create ns pinniped-sup
kapp deploy -y --app pinniped-supervisor --into-ns pinniped-sup --file https://get.pinniped.dev/v0.22.0/install-pinniped-supervisor.yaml
```

Logs from failing pods show:
```
{"level":"info","timestamp":"2023-03-17T11:44:48.663922Z","caller":"go.pinniped.dev/internal/supervisor/server/server.go:678$server.main","message":"Running supervisor","user-agent":"pinniped-supervisor/v0.0.0 (linux/amd64) kubernetes/e6a1897","version":{"major":"0","minor":"0","gitVersion":"v0.0.0","gitCommit":"e6a18978d1fcb2f4615a71cd066e8e3c1e1aa65d","gitTreeState":"clean","buildDate":"2023-01-19T23:53:56Z","goVersion":"go1.19.5","compiler":"gc","platform":"linux/amd64"},"arguments":["pinniped-supervisor","/etc/podinfo","/etc/config/pinniped.yaml"]}
{"level":"error","timestamp":"2023-03-17T11:44:48.669590Z","caller":"go.pinniped.dev/internal/supervisor/server/server.go:703$server.Main","message":"unrecoverable error encountered","error":"cannot create API service ref: cannot get api service v1alpha1.clientsecret.supervisor.pinniped.dev: apiservices.apiregistration.k8s.io \"v1alpha1.clientsecret.supervisor.pinniped.dev\" is forbidden: User \"system:serviceaccount:pinniped-sup:pinniped-supervisor\" cannot get resource \"apiservices\" in API group \"apiregistration.k8s.io\" at the cluster scope"}
```

**In what environment did you see this bug?**
- Pinniped server version: 0.20 and 0.22
- Pinniped client version: n/a
- Pinniped container image (if using a public container image): using projects.registry.vmware.com/pinniped/pinniped-server:v0.22.0@sha256:481b94f4468425542f111143ebb69cd2057b0003e7bee75047892638cf88e135 provided by https://get.pinniped.dev/v0.22.0/install-pinniped-supervisor.yaml
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): n/a
- Kubernetes version (use `kubectl version`): Using Kind v1.24.7
- Kubernetes installer & version (e.g., `kubeadm version`):Kind
- Cloud provider or hardware configuration: Kind
- OS (e.g: `cat /etc/os-release`): Kind on Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-67-generic
- Others:

**What else is there to know about this bug?**

**Comment by joshuatcasey** [comment]
Thanks for reporting this issue. I'll try to reproduce this now with `v0.32.0`.

**Comment by joshuatcasey** [comment]
workaround provided
