### ISSUE TITLE
Documentation on How to use Kubernetes Cluster with Pinniped Auth OIDC with LENS IDE

### ISSUE THREAD

**Issue by viju2008** [vmware-tanzu/pinniped#1464]
**Is your feature request related to a problem? Please describe.**

I am unable to use LENS IDE after implementing Pinniped Auth on my cluster as I am not able to identify how to configure LENS IDE to pop up the LOGIN WEB APPLICATION

I am unable to use LENS IDE as LENS is unable to open the Login GUI of PINNIPED

**Describe the solution you'd like**
Documentation on how to use LENS IDE to view a cluster behined pinniped auth

LENS throws up error due to pinniped auth

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by viju2008** [comment]
Also post authentication with pinniped is it possible to generate a kubeconfig with the authentication token received from pinniped so that it can be directly given to LENS IDE . Operating system WINDOWS 10

**Comment by cfryanr** [comment]
Hi @viju2008, thanks for opening an issue. I'm not familiar with that IDE, but it seems like we should be able to get it working with your help.

Can you share more about your Pinniped configuration? Are you using the Pinniped Supervisor? If so, what kind identity provider is configured for your Supervisor? If not, what is your configuration?

**Comment by cfryanr** [comment]
Hi @viju2008, we didn't hear back from you so I'm closing this issue for now. Please feel free to reopen it once you are able to provide more information about the problem that you are facing.
