### ISSUE TITLE
Add requirement for kube-apiserver not including `--anonymous-auth=false` flag to Concierge docs (when impersonation proxy is not being used)

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1512]
**Is your feature request related to a problem? Please describe.**

When the Concierge is installed on a cluster that does not necessitate the use of the impersonation proxy, then it is important that the cluster's API server'w Pod does not use the command-line option `--anonymous-auth=false` for the `kube-apiserver` CLI binary. This blocks unauthenticated access to the TokenCredentialRequest API of the Concierge, which is the API that unauthenticated users user to auth. This does not matter for the impersonation proxy, which will allow these TokenCredentialRequests requests anyway (but still block all other authenticated requests).

**Describe the solution you'd like**

We should add this detail to the docs. Perhaps add it to here https://pinniped.dev/docs/reference/supported-clusters/ and maybe also here https://pinniped.dev/docs/howto/install-concierge/?

**Additional context**

See Slack thread https://kubernetes.slack.com/archives/C01BW364RJA/p1682955885527879.

The symptom is that kubectl commands will give this error: `Error: could not complete Concierge credential exchange: could not login: Unauthorized` even though everything else is configured correctly and otherwise working fine. The Concierge logs will not show any "TokenCredentialRequest" log statements, because the Kube API server is blocking the requests.

**Comment by smeet07** [comment]
.take-issue

**Comment by smeet07** [comment]
@cfryanr could you assign the issue to me?
