### ISSUE TITLE
Configurable ID expiration time

### ISSUE THREAD

**Issue by giri-varma** [vmware-tanzu/pinniped#1565]
**Is your feature request related to a problem? Please describe.**

Pinniped supervisor is used the Identity Broker in Tanzu Mission Control Self-Managed. The high level workflow is like below,
1. The configures their upstream IdentityProvider in pinniped (mostly OIDCIdentityProvider)
2. The TMC SM clients (CLI & UI) use pinniped-supervisor as the IdP to acquire ID tokens which are then validated by the TMC SM services for user identity (Please note that TMC SM has a stateless session with the ID token being required as part of every API call)

Currently, the pinniped-supervisor issued ID tokens are valid for 5 minutes. This works fine mostly in CLI interactions which are always single threaded. The UI interaction however is more complex where multiple sections of the UI could be making parallel calls. The short token expiration duration complicates the UI design since we now need to have a critical section to refresh the ID token that is common to all UI sections.

**Describe the solution you'd like**

As part of the pinniped-supervisor installation, I would like to configure the expiration duration of the ID token. Say, I can configure the duration to be 30 minutes, then the UI only needs to refresh the ID token only every 30 minutes. This does not completely remove the need for a critical section in the UI, but provide more flexibility for the UI.

Additionally, this can reduce the load on the K8s cluster where TMC SM is installed when there are a lot of parallel users.

**Describe alternatives you've considered**

We have considered 3 alternatives:
1. Add a critical section to the UI - We are in the middle of this fix but is proving to be trickier than originally thought.
2. Use a different IdP broker - Pinniped has been very easy to configure and ship otherwise. So, prefer not to switch to a different broker for this one issue.
3. Implement TMC's own session management and require the pinniped ID token only for login - This is a significant project by itself and not achievable in the near term.

**Comment by joshuatcasey** [comment]
@giri-varma has this been resolve with #1914 for `OIDCClients` (released in [v0.30.0](https://github.com/vmware-tanzu/pinniped/releases/tag/v0.30.0)).

**Comment by giri-varma** [comment]
Thanks @joshuatcasey! v0.30.0 seems to address the requirement. We will try the new version.

**Comment by joshuatcasey** [comment]
We'll close this since the requested feature has been released. We'll work internally to validate if necessary.
