### ISSUE TITLE
Document how to debug LDAPIdentity provider spec using `ldapsearch` CLI and pod logs

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1581]
**Is your feature request related to a problem? Please describe.**

Often the best way to debug the spec of an LDAPIdentityProvider that's not working is to manually transcribe the settings into arguments of the `ldapsearch` CLI and try running some searches. This requires good knowledge of both how Pinniped forms user search and group search queries, and how the ldapsearch CLI works.

**Describe the solution you'd like**

A doc could describe how to perform this type of debugging.

- How to find relevant log messages in the Supervisor pod logs after a failed login attempt.
- How to translate your settings to ldapsearch commands to try the similar user search and group search yourself.

**Describe alternatives you've considered**

Maybe there could even be a shell script in the hack directory to perform the translation from LDAPIdentityProvider into the ldapsearch commands.

**Comment by joshuatcasey** [comment]
This seems resolved in #1594
