### ISSUE TITLE
`pinniped get-kubeconfig` double-prints error messages

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#160]
**What happened?**

I run `pinniped get-kubeconfig` and it prints the error message twice.

```
pivotal@akeesler-a01:enhancements$ pinniped get-kubeconfig
Error: required flag(s) "token" not set
required flag(s) "token" not set
```

```
pivotal@akeesler-a01:enhancements$ pinniped get-kubeconfig --token whatever --pinniped-namespace integration --idp-type webhook
Error: no identity providers were found in namespace "integration"
no identity providers were found in namespace "integration"
```

**What did you expect to happen?**

I run `pinniped get-kubeconfig` and it prints the error message once.

```
pivotal@akeesler-a01:enhancements$ pinniped get-kubeconfig
Error: required flag(s) "token" not set
```

```
pivotal@akeesler-a01:enhancements$ pinniped get-kubeconfig --token whatever --pinniped-namespace integration --idp-type webhook
Error: no identity providers were found in namespace "integration"
```

**What is the simplest way to reproduce this behavior?**

Run `pinniped get-kubeconfig`.

**In what environment did you see this bug?**
- Pinniped server version: n/a
- Pinniped client version: https://github.com/vmware-tanzu/pinniped/releases/tag/v0.1.0
- Pinniped container image (if using a public container image): n/a
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): n/a
- Kubernetes version (use `kubectl version`): n/a
- Kubernetes installer & version (e.g., `kubeadm version`): n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Others: n/a

**What else is there to know about this bug?**

Whoever fixes this might want to check and see if our CLI double prints error messages in other cases.

**Comment by rajat404** [comment]
I'd like to work on this 🙋🏽 
LMK if that's okay :)

**Comment by ankeesler** [comment]
Go for it @rajat404! Thanks for your interest!

**Comment by rajat404** [comment]
Just wanted to clarify if `v0.1.0` client is still supported or not? 
Asking coz it was the initial release. Not sure how long after release, the client is maintained.

**Comment by rajat404** [comment]
Also, given that this issue is for client v0.1.0, how should I make the commit?

Should I fork from `tags/v0.1.0` and then make the change, or should I commit on master?

**Comment by ankeesler** [comment]
@rajat404 - you did the right thing to target `main` in your PR. Thank you!

**Comment by ankeesler** [comment]
Ah! Sorry! I closed this too early! I'll wait until your PR is merged.
