### ISSUE TITLE
Actually respect `klog` logging flags

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#161]
**What is the problem that you wish to solve?**

- I wish there was a way to enable more verbose logging in `pinniped` components so that I could better understand what is going on in the code.
- There are a couple places in our code where we use verbose logging (e.g., [here](https://github.com/vmware-tanzu/pinniped/blob/87c7e9a55602d4df3e4d88a38f9594ba7261d14b/internal/controllerlib/option.go#L65)).
- There are a couple places in our code where we would _like_ to use more verbose logging (e.g., observing when a controller does specific stuff and how long that takes).

**What is the best solution to the above problem?**

- Reuse `klog` logging flags.
- Our logging solution, `klog`, automatically provides some flags to enable this verbose logging (see [`k8s.io/component-base.init`](https://github.com/kubernetes/component-base/blob/master/logs/logs.go#L35)).

**What are the alternative solutions that you have considered?**

- Enable verbose logging all the time - seems like we don't _always_ want verbose logging since this often obscures the most interesting log messages to 90% of the population.

**How will this project improvement be tested?**

Good question...

**In what environment do you hope to see this improvement?**
- Pinniped server version: latest
- Pinniped client version: latest
- Pinniped container image (if using a public container image): latest
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): all IDPs
- Kubernetes version (use `kubectl version`): latest
- Kubernetes installer & version (e.g., `kubeadm version`): latest
- Cloud provider or hardware configuration: all (this solution should be platform agnostic)
- OS (e.g: `cat /etc/os-release`): all (this solution should be platform agnostic)
- Kernel (e.g. `uname -a`): all (this solution should be platform agnostic)
- Others:

**What else is there to know about this improvement?**

 None.

**Comment by enj** [comment]
See https://github.com/kubernetes/kubernetes/pull/63777 and https://github.com/kubernetes/kubernetes/pull/64601 for ideas...

**Comment by ankeesler** [comment]
Could be part of this story: Should we consider logging `"oidc provider manager examining request"` at a higher verbosity? It really fills up the logs...

**Comment by ankeesler** [comment]
@enj did this here: https://github.com/vmware-tanzu/pinniped/pull/190.
