### ISSUE TITLE
The pinniped-concierge-kube-cert-agent hard coded to specific control plane node causes problems when node is unavailable

### ISSUE THREAD

**Issue by trouphaz** [vmware-tanzu/pinniped#2137]
**What happened?**

One of our control plane nodes was no longer functional and happened to be the node where the pinniped-concierge-kube-cert-agent pod was running.  When trying to restart the pod we found it would only restart on the same node.  With this pod offline, the pinniped-concierge pods would fail.  These were the errors we originally saw in the pinniped-concierge pods before restarting because of underlying node problems.  The pods seemed to be ok, but all underlying storage was read only.

{"level":"error","timestamp":"2024-11-20T21:46:43.731956Z","caller":"go.pinniped.dev/internal/controllerlib/controller.go:219$controllerlib.(*controller).handleKey","message":"kube-cert-agent-controller: { } failed with: [could not exec into agent pod pinniped-concierge/pinniped-concierge-kube-cert-agent-68cb648c7d-42d6q: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"c6bd2e1dda74be59b43d0a052ca6e24a5d8a1f6c491e449a3bb6c9d1bb797a4b\": OCI runtime exec failed: open /tmp/runc-process1278122503: read-only file system: unknown, failed to update CredentialIssuer status: Put \"https://198.19.0.1:443/apis/config.concierge.pinniped.dev/v1alpha1/credentialissuers/pinniped-concierge-config/status\": middleware request for &kubeclient.request{verb:\"update\", namespace:\"\", resource:schema.GroupVersionResource{Group:\"config.concierge.pinniped.dev\", Version:\"v1alpha1\", Resource:\"credentialissuers\"}, reqFuncs:[]func(kubeclient.Object) error{(func(kubeclient.Object) error)(0x1e55a40)}, respFuncs:[]func(kubeclient.Object) error(nil), subresource:\"status\"} failed to mutate: request mutation failed: write attempt rejected as client is not leader]\n"}

**What did you expect to happen?**

Before realizing that the deployment had a single control plane node hard coded into the pinniped-concierge-kube-cert-agent deployment, we expected that the pod would just restart elsewhere.

**What is the simplest way to reproduce this behavior?**

The behavior is just how the concierge is coded.  The kube-cert-agent-controller deployment is always hard coded to be colocated with the newest kube-controller-manager pod:

This is where nodeName is set to match the kube-controller-manager pod: https://github.com/vmware-tanzu/pinniped/blob/v0.35.0/internal/controller/kubecertagent/kubecertagent.go#L585

Tracks back to this function where it finds the newest kube-controller-manager pod: https://github.com/vmware-tanzu/pinniped/blob/v0.35.0/internal/controller/kubecertagent/kubecertagent.go#L494

**In what environment did you see this bug?**
- Pinniped server version: v0.22.0, but it seems like it still exists in v0.35.0
- Pinniped client version: v0.33.0
- Pinniped container image (if using a public container image): pinniped-server:v0.22.0
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`): v1.25.13
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**
One workaround has simply been to delete the kube-controller-manager pod on a healthy control plane node and let it restart.  Then monitor the pinniped-concierge-kube-cert-agent pod because the deployment should be automatically updated and the pod rescheduled on the new node.  (edited to reflect testing.  showed that pinniped-concierge automatically updates the deployment and the pod gets rescheduled without having to delete the deployment.)

**Comment by cfryanr** [comment]
Thanks for reporting this detailed issue and workaround @trouphaz!

> One of our control plane nodes was no longer functional

Are you able to characterize the way that it was not functional? Was it non-functional in some way that Kubernetes recognized and started automatically rescheduling the other pods to move the away from that node? Did Kubernetes mark the node in any way to indicate that there was a problem? The nature of the problem on the node would probably influence the design of any potential new feature in the Concierge that tries to make this situation better.

> When trying to restart the pod we found it would only restart on the same node.

Were you deleting the pod, or something else? Curious how you had hoped that it would work.

**Comment by trouphaz** [comment]
@cfryanr, our clusters are built on VMware.  Our clusters are built on 3 sets of hardware (network switches, compute and storage) each configured as a separate availability zone with our control plane nodes distributed across the 3.  One AZ was in a bad state, so its CP node was up and running but with read-only disk.
We deleted the kube-cert-agent-controller pod, assuming it would be rescheduled elsewhere when we cordoned the CP node, but it just kept getting scheduled in the same location.  That was when we realized the deployment had the nodeName parameter set to that specific CP node.  Knowing this CP node would be in a bad state for hours while we repaired damaged network and SAN equipment, we had to find a way to get the kube-cert-agent-controller to be scheduled elsewhere.

Our issue was fairly specific to our cluster design, but being able to relocate the kube-cert-agent-controller pod to another node seems like something others may be interested in for other reasons.

**Comment by cfryanr** [comment]
> assuming it would be rescheduled elsewhere when we cordoned the CP node

How did you cordon the node? Maybe Pinniped can watch for that.

**Comment by trouphaz** [comment]
> > assuming it would be rescheduled elsewhere when we cordoned the CP node
> 
> How did you cordon the node? Maybe Pinniped can watch for that.

We just used `kubectl cordon <node>`.  If the kube cert agent pod just needs to run on any CP node, could this be added to the deployment spec instead of tracking where the kube-controller-manager pod is?  This will force the pod to start on a control plane node.  This won't work if the pod needs to be colocated with the newest kube-controller-manager pod though.
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
```

**Comment by cfryanr** [comment]
@trouphaz I drafted a potential solution here: https://github.com/vmware-tanzu/pinniped/pull/2143. Please take a look at the PR's description and let me know what you think when you get a chance.
