### ISSUE TITLE
The `TestSupervisorLogin` integration test can be flaky.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#228]
**What happened?**

The `TestSupervisorLogin` test failed on [a PR CI test run](https://hush-house.pivotal.io/builds/9006057):

```
=== RUN   TestSupervisorLogin
    supervisor_login_test.go:41: created test OIDCProvider supervisor/test-oidc-provider-zrtnr
    supervisor_login_test.go:79: created test client credentials Secret test-client-creds-fthnc
    supervisor_login_test.go:82: created test UpstreamOIDCProvider test-upstream-v7p7j
    supervisor_login_test.go:92: 
        	Error Trace:	supervisor_login_test.go:92
        	Error:      	Not equal: 
        	            	expected: 302
        	            	actual  : 422
        	Test:       	TestSupervisorLogin
    supervisor_login_test.go:41: cleaning up test OIDCProvider supervisor/test-oidc-provider-zrtnr
--- FAIL: TestSupervisorLogin (1.96s)
```

**What did you expect to happen?**

The test should succeed!

**What is the simplest way to reproduce this behavior?**

I think we should be able to reliably reproduce this flake if we add an artificial delay to the `upstream-observer` controller sync method.

**In what environment did you see this bug?**

This occurred on the PR tests for commit ad1bc6c36cbdfdbe9ec19a3da3394f185a095051.

**What else is there to know about this bug?**

We can probably fix this by adding the appropriate `require.Eventually(...)` call to the assertion block that's failing.

**Comment by anjaltelang** [comment]
Not seeing this issue. We can open a new issue to track if we see this again.
