### ISSUE TITLE
Refactor docs/website to organize and avoid duplication.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#235]
**Is your feature request related to a problem? Please describe.**

Our markdown documentation and website source code has a lot of duplicate content right now.

**Describe the solution you'd like**

We should find some clean way of making a single canonical source for our core documentation. This might be as simple as deleting the non-website copy of docs, or it could be something along the lines of an expanded build script for the website.

**Comment by rajat404** [comment]
May I pick this? 🙋🏽‍♂️

**Comment by rajat404** [comment]
Given that everyone would be AFK over the weekend, I'm taking the liberty to pick this 😅
