### ISSUE TITLE
Fuzz fosite config struct

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#240]
We need a way to track if the [fosite config](https://github.com/ory/fosite/blob/c4c1e6fd9e26e26de9e8c5ee490498ddef39291f/compose/config.go#L31) grows new knobs for us to tweak.  The simplest approach to me would be to deterministically fuzz it and then encode it into JSON for diffing similar to:

https://github.com/vmware-tanzu/pinniped/blob/86865d155a4dff3a76b43b46deb9e16283290c3d/internal/fosite/authorizationcode/authorizationcode_test.go#L204

**Comment by anjaltelang** [comment]
Decided not to pursue this implementation
