### ISSUE TITLE
In local development flows, Tilt is unable to perform live-reload.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#248]
**What happened?**

When I'm using Tilt to do local development (`./hack/kind-up.sh && ./hack/tilt-up.sh`), when I edit a `.go` source file, I see that Tilt is falling back to a full rebuild:

```
Will copy 1 file(s) to container: e708205333
- '/Users/moyerm/vmware-tanzu/pinniped/hack/lib/tilt/build/pinniped-supervisor' --> '/usr/local/bin/pinniped-supervisor'
tar: usr/local/bin/pinniped-supervisor: Cannot open: File exists
tar: Exiting with failure status due to previous errors

Live Update failed with unexpected error:
	command terminated with exit code 2
Falling back to a full image build + deploy
```

The full rebuild still works correctly, but is somewhat slow.

**What did you expect to happen?**

I expected Tilt to perform a live reload without needing to build fresh images or rollout new pods, in most cases. This should be much faster.

**What is the simplest way to reproduce this behavior?**

Run `./hack/kind-up.sh && ./hack/tilt-up.sh`, then edit a Go source file under one of the Pinniped components. You can see the above error message in the Tilt output (web or console streaming).

**In what environment did you see this bug?**

I see this on the current `main` branch head (385d2db445e413e833201a7411cb8564ccc69379). 

**What else is there to know about this bug?**

We had one attempted fix in 2e50e8f01bf1653340d1ad01de7fde440d3ee19d, but I think we missed another bit of config which still causes our pods to run as non-root users:

https://github.com/vmware-tanzu/pinniped/blob/be8f11fe5acbeb5e932c045510bea43c9cbe7e1e/deploy/supervisor/deployment.yaml#L65-L68

I believe we need to add ytt conditionals for excluding those lines in our Tilt deployment. There are similar lines in the concierge and local-user-authenticator deployments as well.

**Comment by ankeesler** [comment]
PR: https://github.com/vmware-tanzu/pinniped/pull/326.
