### ISSUE TITLE
Consider adding caching to `dynamicOpenIDConnectECDSAStrategy` to reduce memory overhead

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#254]
**Is your feature request related to a problem? Please describe.**
Every time `dynamicOpenIDConnectECDSAStrategy.GenerateIDToken()` is called (i.e.,  every time we issue an ID token), we call `compose.NewOpenIDConnectECDSAStrategy(s.fositeConfig, key)`. We don't necessarily need to call this constructor every time, since the `s.fositeConfig` and `key` may be the same as the last time that `dynamicOpenIDConnectECDSAStrategy.GenerateIDToken()` was called.

See https://github.com/vmware-tanzu/pinniped/pull/249/files#diff-81c6a81fe5a22ee2ceab532b3aba3af58fa78b283bd98c07db18950aa5ea9f00R51.

**Describe the solution you'd like**
Cache the values of `compose.NewOpenIDConnectECDSAStrategy(s.fositeConfig, key)` per `s.fositeConfig` and `key` so we don't allocate a whole new struct every time `dynamicOpenIDConnectECDSAStrategy.GenerateIDToken()` is called.

**Describe alternatives you've considered**
Right now, we aren't doing this because we are trying to simplify our implementation. It could be the case that this is OK and doesn't cause the memory pressure that we think it does. But it seems wasteful to call `compose.NewOpenIDConnectECDSAStrategy(s.fositeConfig, key)` many times where we could just reuse the return value from the first call.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- Unit test that checks a local cache for the `dynamicOpenIDConnectECDSAStrategy` to make sure it is using the cache properly.

- **How does this change the current architecture?**
- It doesn't.

- **How will this change be backwards compatible?**
- It doesn't affect user-facing functionality.

- **How will this feature be documented?**
- It is an internal implementation change, so it doesn't necessarily need any documentation. However, we could add a release note that we have reduced memory usage after this change.

**Additional context**

This came about when @margocrawf and I were working on the token endpoint.

**Comment by anjaltelang** [comment]
This issue does not impact in practice.
