### ISSUE TITLE
Add demo for using Pinniped with an upstream OIDC provider

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#256]
**Is your feature request related to a problem? Please describe.**
Our OIDC federation design is not trivial. It will help folks to build a mental model of how it works by following a demo (like we have with the Concierge/`WebhookAuthenticator`).

**Describe the solution you'd like**
A demo that shows how to set up the Supervisor and the Concierge (using a `JWTAuthenticator`) to validate Supervisor tokens.

**Describe alternatives you've considered**
N/A

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by mattmoyer** [comment]
This should be covered by other docs issues we have open (e.g., #417).
