### ISSUE TITLE
JWTAuthenticator takes 10 seconds to warm up

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#260]
**What happened?**

When I create/update a `JWTAuthenticator`, it takes 10 seconds to initialize since we use Kube's [`oidc.Authenticator`](https://github.com/kubernetes/kubernetes/blob/e1c617a88ec286f5f6cb2589d6ac562d095e1068/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go). Therefore, when I create a `login.concierge.pinniped.dev/v1alpha1.TokenCredentialRequest` in that 10 second window, I get a response with `"authentication failed"` and an underlying log message of `"oidc: authenticator not initialized"`.

**What did you expect to happen?**

I want to be able to start using a `JWTAuthenticator` immediately after creating/updating it.

**What is the simplest way to reproduce this behavior?**

1. Create a `JWTAuthenticator`.
1. Within 10 seconds, create a `TokenCredentialRequest` referring to that `JWTAuthenticator` with a valid ID token.
1. You should see that authentication failed.
1. To convince yourself that the ID token is valid, wait 10 seconds, and then create the `TokenCredentialRequest` again, and see that it succeeds.

**In what environment did you see this bug?**
- Pinniped server version:
- Pinniped client version:
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**

This came up during development of https://github.com/vmware-tanzu/pinniped/pull/258. We wanted to use Kube's Kube's [`oidc.Authenticator`](https://github.com/kubernetes/kubernetes/blob/e1c617a88ec286f5f6cb2589d6ac562d095e1068/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go) to get the benefit of that code, but the 10 second timeout is a bummer.

**Comment by enj** [comment]
> I want to be able to start using a `JWTAuthenticator` immediately after creating/updating it.

This will never be true.  There will always be some delay between you creating a `JWTAuthenticator` and the cache being up to date if you use a CRD.  You could create an aggregated API that blocks create/update calls until the authenticator is ready, but that would be a very different implementation.  The delay in the Kube code just guarantees a cache miss instead of it being uncommon.

**Comment by ankeesler** [comment]
> This will never be true.

OK, fair, `immediately` is a little aggressive. Maybe instead of `immediately`, I mean some single digit number of seconds.

**Comment by mattmoyer** [comment]
Should we try to tweak the upstream library or just do our own validator?

I think we might eventually want to add additional validation behavior that would require bringing this in-house anyway.

**Comment by cfryanr** [comment]
Unless/until we need to write our own validations, could we perhaps simply document that this 10 second delay is the expected behavior and mark this as will not fix? That would remove this item from our growing todo list. :)

**Comment by mattmoyer** [comment]
@enj is going to take a shot at fixing this upstream (it's roughly a one-line change).

**Comment by enj** [comment]
https://github.com/kubernetes/kubernetes/pull/97693 is merged.  We will pick it up when we bump our deps to 1.21.  It does not warrant a backport to earlier releases of Kube.

**Comment by mattmoyer** [comment]
Now that we've upgraded to v1.21, we can remove a 10s sleep from one of our integration tests.
