### ISSUE TITLE
Document the deployment, configuration, and usage of the Supervisor

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#307]
**Acceptance Criteria**

*GIVEN* I want to learn about the Pinniped Supervisor
*WHEN* I go to the [Pinniped README.md](https://github.com/vmware-tanzu/pinniped)
*THEN* I can learn a little bit about what the Supervisor is and why I should care
*AND* I can still learn a little bit about what the Concierge is and why I should care (this documentation should already exist!)
*AND* I know where to go to get a deeper understanding of the Supervisor
*AND* I know where to go to get a deeper understanding of the Concierge (this documentation should already exist!)
*AND* I know where to go to run a demo of the Supervisor
*AND* When I run the demo of the Supervisor, it works

**Comment by ankeesler** [comment]
Docs: https://github.com/vmware-tanzu/pinniped/pull/297 
More docs: https://github.com/vmware-tanzu/pinniped/pull/306
Demo: https://github.com/vmware-tanzu/pinniped/pull/310

**Comment by ankeesler** [comment]
The above PRs are merged. This is ready for review.
