### ISSUE TITLE
Issue federation ID tokens with group claim as an array

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#323]
**What happened?**

- @enj and I were working on https://github.com/vmware-tanzu/pinniped/pull/322.
- We noticed that we issue downstream ID tokens with a `groups` claim formatted either as an array or a string: https://github.com/vmware-tanzu/pinniped/blob/3f08f2e11e5c0599984f16d6b15c5bc2f364ef98/internal/oidc/callback/callback_handler.go#L275-L276.
- We should be consistent about the data type for our downstream `groups` claim.

**What did you expect to happen?**

- We should be consistent about the data type we use for our downstream `groups` claim.
- We should always use an array.

**What is the simplest way to reproduce this behavior?**

**In what environment did you see this bug?**
- Pinniped server version: `v0.3.0`
- Pinniped client version: n/a
- Pinniped container image (if using a public container image): n/a
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): n/a
- Kubernetes version (use `kubectl version`): n/a
- Kubernetes installer & version (e.g., `kubeadm version`): n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Others: n/a

**What else is there to know about this bug?**

- We should also try to cast `groupsAsInterface` to an `[]interface{}` in the case that the upstream token has been unmarshaled that way.

**Comment by margocrawf** [comment]
I'm wondering how many possible scenarios we want to cover with this change.

The groups claim could be anything so it seems difficult to anticipate every possible format we might get from the upstream token. 

Currently in our tests we have the following examples:

1. slice of strings
2. A string separated by spaces (e.g. "group1 group2")
3. An integer (results in unprocessable entity)

It seems reasonable to try to parse 2. into a slice, but are there are other possible formats we should be worried about?

**Comment by enj** [comment]
I do not think we should support anything more than `string` and `[]string` from the upstream IDP group claim.  We should try to parse the input as `[]interface` simply because all the elements may still be a string, i.e. `[]interface{"group1", "group2"}` should work.

For the downstream token, we should guarantee that the `groups` claim is always a `[]string`.  @mattmoyer seemed to be leaning towards `[]` over omitting the claim when the user has no groups which I think is reasonable.
