### ISSUE TITLE
Supervisor has an LDAPIdentityProvider.idp.supervisor.pinniped.dev CRD

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#336]
**Purpose:** A first step toward the Supervisor supporting LDAP servers as an upstream IDP type.

**GIVEN** I have installed the Pinniped Supervisor
**WHEN** I kubectl create LDAPIdentityProvider
**THEN** it is created
**AND** I can read it, delete it, etc.

Details of the fields allowed in the CRD TBD (see [previous research from the team](https://gist.github.com/mattmoyer/c089ef0cefb24c538cdebe5af7451c45#file-03-idp-config-sample-ldap-yaml)).

**Comment by mattmoyer** [comment]
This should be covered by https://github.com/vmware-tanzu/pinniped/issues/440.
