### ISSUE TITLE
Simple browser-based LDAP login page

### ISSUE THREAD

**Issue by margocrawf** [vmware-tanzu/pinniped#337]
**Purpose:** LDAP identity providers will not have their own web pages configured for us to redirect to, so we will need to present pinniped users with our own simple login page that prompts them for their LDAP login.

**Given** that I have an `LDAPIdentityProvider` configured with Pinniped
**And given** I have configured my kubeconfig to use pinniped
**When** I run `kubectl` commands
**Then** my browser opens a login page hosted by the supervisor that prompts me for my LDAP username and password

Styling is out of scope for this story.

**Comment by mattmoyer** [comment]
We ended up deciding to go with a CLI-driven password prompt in #440, so I think this is no longer in the immediate plans. I'll leave it here because we did discuss doing this at some point in the future.
