### ISSUE TITLE
Add minimal impersonation proxy as an alternative strategy for concierge on managed clusters

### ISSUE THREAD

**Issue by margocrawf** [vmware-tanzu/pinniped#339]
**Purpose** This will allow Pinniped to work on more kinds of clusters. Today, the concierge only provides access to a cluster if it can access the cluster signing key, which is not possible on many cloud providers' clusters. An impersonation proxy will allow the user to provide a JWT token to make calls to the kube api server without the concierge having to issue a cluster specific certificate. 

**Given** that I have a GKE cluster configured with Pinniped
**And given** that I have configured my kubeconfig to use the impersonation proxy as the kube API server
**And given** that I have configured my kubeconfig to use the Pinniped CLI with an OIDC provider
**When** I run `kubectl get` commands
**Then** my commands execute as my identity from the OIDC provider
**And** my commands are effected by the RBAC settings for my identity

Notes: Additional scope will be part of later stories.
- #67 was a draft version that we can look at for reference.
- Configuration of the proxy is out of scope.
- Group membership is out of scope.
- JWT validation is out of scope.
- Assume that the username will always be at the claim `username`.
- Do the simplest possible thing to get kubectl to accept our TLS configuration (or lack thereof)

**Comment by mattmoyer** [comment]
Some notes about this and possible followup stories (brainstorming with @cfryanr):
1. Assume manually-created kubeconfig, don't really validate the tokens at all, disable behind a feature gate. Add basic token validation using the JWT/webhook token authenticator cache, impersonate the right username and groups. This is basically this current issue, but with a little additional scope to make sure we can safely merge to `main` without opening any serious security issues, and avoids us having to build some other mechanism to disable/enable the code dynamically.
3. Wire in some configuration via Credentialssuer spec for whether/how to start the proxy, including manually specified TLS certificates (in a Secret)
4. Publish status about the proxy into the CredentialIssuer status.
5. Add a flag to the `pinniped login oidc`/`pinniped login static` commands like `--enable-concierge-proxy` which skips the TokenCredentialRequest exchange and instead returns the token in the right format to pass to the proxy. The name/type of token authenticator should be embedded in the bearer token somehow.
6. Add code to the `pinniped get kubeconfig` that allows it to detect the "proxy mode" and output an appropriate kubeconfig.

Possible future stories (might be out of scope of the main requirements):
1. Add code to automatically create a LoadBalancer service if requested in the CredentialIssuer (e.g., "mode: auto")
2. Add code to automatically generate a CA and sign the proxy certs.
