### ISSUE TITLE
Supervisor token refresh should fail when the upstream refresh token no longer works for LDAP and AD 

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#340]
**Purpose:** Today, the duration of a downstream Supervisor refresh session is 9 hours. Once you have logged in to your upstream IDP, your downstream session remains valid for 9 hours even if your session or user account in the upstream IDP is revoked. Instead, during the next downstream token refresh, the Supervisor should notice that your upstream session is no longer valid and the refresh should fail, which will cause the CLI to start a new login flow for the user.

**Given** that I am running a Supervisor with an upstream LDAP or AD IDP configured,
**And given** that I have already used the Pinniped CLI to get tokens from the Supervisor,
**And given** that I wait long enough for my downstream access token and my upstream refresh token to expire (but less than 9 hours) **or** I otherwise cause my upstream session to expire (revoke the session or disable the user account or whatever)
**When** I use the Pinniped CLI to refresh my downstream session
**Then** I am returned to the login page of my provider, and I can successfully log in again to get new tokens

Notes:
- Refreshing group membership is out of scope and will be addressed by a future issue
- As part of this PR the Supervisor refresh sessions durations can be extended to more like 12 or 16 hours, which would be a reasonable default considering that the upstream IDP can effectively override it by having shorter refresh session durations if desired. 12 or 16 hours is long enough that it will cover a whole work day, but short enough that it will not cover any part of the next work day.
- Possible implementation for LDAP:
  - Record DN on initial login
  - Assert that the LDAP entry still exists
  - Assert that the configured UID field is unchanged in LDAP (i.e. assert that our downstream sub claim would not change)
  - Assert that the configured Username field is unchanged in LDAP
- Possible implementation for AD:
  - All of the same checks as LDAP
  - Assert that the user is not disabled via the userAccountControl field
  - Assert that the user's password has not changed since the initial login via the pwdlastset field
  - Assert that the user's password has not expired since the initial login via the userAccountControl field
  - Assert that the user’s account is not currently locked out via the userAccountControl field

**Comment by anjaltelang** [comment]
For AD specific implementation see https://github.com/vmware-tanzu/pinniped/issues/887
