### ISSUE TITLE
Design: multiple IDP support

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#352]
TODO

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by cfryanr** [comment]
Started a design document here: https://hackmd.io/bPcs_c2ZR8WnpcuQ73FC-w?view

**Comment by cfryanr** [comment]
Done. See https://github.com/vmware-tanzu/pinniped/tree/main/proposals/1406_multiple-idps
