### ISSUE TITLE
Design: browser-less (and possibly password-less) CLI SSO

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#354]
TODO

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by mattmoyer** [comment]
I think we're tackling this in the design for the LDAP identity provider in #440. Closing but feel free to reopen if you think there's additional design work beyond what we're doing for that story.

**Comment by enj** [comment]
Should we open a new story for future Active Directory with Kerberos support (i.e. CLI SSO)?
