### ISSUE TITLE
Do we need to remove `TokenCredentialRequest` from `pinniped` category?

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#371]
**What happened?**

- I am running the Concierge with a `JWTAuthenticator` in the `pinniped-concierge` namespace.
- I ran `kubectl get pinniped` and got this:
```
akeesler@akeesler-a02:pinniped-ci$ k get pinniped
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
```
- I ran `kubectl get pinniped -n pinniped-concierge` and got this:
```
akeesler@akeesler-a02:pinniped-ci$ k get pinniped -n pinniped-concierge
NAME                                                                           ISSUER
jwtauthenticator.authentication.concierge.pinniped.dev/tkg-jwt-authenticator   https://af0c3cd46a7c2415c835317675239b96-1968935863.us-east-1.elb.amazonaws.com

NAME                                                                       AGE
credentialissuer.config.concierge.pinniped.dev/pinniped-concierge-config   14m
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
```
- I ran `kubectl get pinniped -A` and got this:
```
akeesler@akeesler-a02:pinniped-ci$ k get pinniped -A
NAMESPACE            NAME                                                                           ISSUER
pinniped-concierge   jwtauthenticator.authentication.concierge.pinniped.dev/tkg-jwt-authenticator   https://af0c3cd46a7c2415c835317675239b96-1968935863.us-east-1.elb.amazonaws.com

NAMESPACE            NAME                                                                       AGE
pinniped-concierge   credentialissuer.config.concierge.pinniped.dev/pinniped-concierge-config   15m
Error from server (NotFound): Unable to list "login.concierge.pinniped.dev/v1alpha1, Resource=tokencredentialrequests": the server could not find the requested resource
```

**What did you expect to happen?**

- I don't want to see those `Error`'s show up when I `get` the `pinniped` categories

**What is the simplest way to reproduce this behavior?**

- `cd` into the `pinniped` repo
- `./hack/prepare-for-integration-tests.sh`
- Do this:
```
cat <<EOF | kubectl apply -f -
kind: JWTAuthenticator
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
metadata:
  name: whatever
  namespace: concierge
spec:
  issuer: https://whatever.tld
  audience: whatever
EOF
```
- `kubectl get pinniped -A` (you should see an `Error`)
- `kubectl get pinniped -n concierge` (you should see an `Error`)
- `kubectl get pinniped` (you should see an `Error`)

**In what environment did you see this bug?**
- Pinniped server version: `v0.4.1`
- Pinniped client version: N/A
- Pinniped container image (if using a public container image): `v0.4.1`
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): `v0.4.1`
- Kubernetes version (use `kubectl version`): `0.20.1`
- Kubernetes installer & version (e.g., `kubeadm version`): N/A
- Cloud provider or hardware configuration: `kind` (`docker`)
- OS (e.g: `cat /etc/os-release`): macOS
- Kernel (e.g. `uname -a`): macOS
- Others:

**Comment by enj** [comment]
IMO this is a bug in how `kubectl get` does category expansion.  In this context it should ignore resources that do not support the `list` verb.
