### ISSUE TITLE
Race and cache mutation detector should be enabled in integration test binaries

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#380]
**Is your feature request related to a problem? Please describe.**

We run a lot of controllers meaning races are easily to accidentally write.

**Describe the solution you'd like**

Our server binaries should run with the race detector (build flag) and cache mutation detector (env var) enabled so that we can catch race conditions in our controllers.

**Describe alternatives you've considered**

None.

**Are you considering submitting a PR for this feature?**

N/A

- **How will this project improvement be tested?**

It would be part of our test infra itself.

- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by mattmoyer** [comment]
This also includes the CLI binary we use in our tests.

**Comment by anjaltelang** [comment]
This is a low priority. Integration test changes will capture this at some point. We can open it again if needed.
