### ISSUE TITLE
Stub: token credential requests should reject authentication on no matching authorization

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#384]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by mattmoyer** [comment]
Closing as a dupe of https://github.com/vmware-tanzu/pinniped/issues/557.
