### ISSUE TITLE
Pinniped should support a `whoami` style API

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#402]
**Is your feature request related to a problem? Please describe.**

It is difficult to understand what identity you are currently using without some form of API to echo back this information.  Such an API would be useful in testing, and would be useful for end users to understand what identity they are currently using (especially when they have many clusters/users as contexts in their kubeconfig).

**Describe the solution you'd like**

The concierge should support an aggregated API that can:

1. Present all the kube specific information
2. Respond with Pinniped specific information as well

```go
type WhoAmIRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WhoAmIRequestSpec   `json:"spec,omitempty"`
	Status WhoAmIRequestStatus `json:"status,omitempty"`
}

type WhoAmIRequestSpec struct {
	// maybe add stuff in the future
}

type WhoAmIRequestStatus struct {
	Kubernetes KubernetesUserInfo `json:"kubernetes"`
	Pinniped  *PinnipedUserInfo   `json:"pinniped,omitempty"`
}

type KubernetesUserInfo struct {
	// standard kube user info data with no special interpretation
}

type PinnipedUserInfo struct {
	// pinniped specific info like what authenticator was used and what upstream IDP was used
}
```

**Describe alternatives you've considered**

N/A

**Are you considering submitting a PR for this feature?**

N/A

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by mattmoyer** [comment]
Validated on a kubeadm-based cluster:
```cmd
$ echo '{"apiVersion": "identity.concierge.pinniped.dev/v1alpha1", "kind": "WhoAmIRequest"}' | kubectl create -o yaml -f -
apiVersion: identity.concierge.pinniped.dev/v1alpha1
kind: WhoAmIRequest
metadata:
  creationTimestamp: null
spec: {}
status:
  kubernetesUserInfo:
    user:
      groups:
      - system:masters
      - system:authenticated
      username: kubernetes-admin
```

As well as a GKE cluster:
```cmd
$ echo '{"apiVersion": "identity.concierge.pinniped.dev/v1alpha1", "kind": "WhoAmIRequest"}' | kubectl create -o yaml -f -
apiVersion: identity.concierge.pinniped.dev/v1alpha1
kind: WhoAmIRequest
metadata:
  creationTimestamp: null
spec: {}
status:
  kubernetesUserInfo:
    user:
      extra:
        iam.gke.io/user-assertion:
        - [...]
        user-assertion.cloud.google.com:
        - [...]
      groups:
      - system:authenticated
      username: moyerm@gcp.vmware.com
```
