### ISSUE TITLE
Test flake in TestGetPinnipedCategory/TestKubeClientOwnerRef

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#408]
**What happened?**

The `TestGetPinnipedCategory` test flakes sometimes.
- Example: https://hush-house.pivotal.io/builds/24421260#L6023aed7:830
- Note: I actually saw this test flake happen locally at 5b076e7421a9fe8251098637c3648e01c362c584 by running `./hack/prepare-for-integration-tests.sh -c && source /tmp/integration-test-env && ./hack/module.sh test`

**What did you expect to happen?**

The test passes consistently.

**What is the simplest way to reproduce this behavior?**

**In what environment did you see this bug?**
- Pinniped server version:
- Pinniped client version:
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**

**Comment by ankeesler** [comment]
https://hush-house.pivotal.io/builds/26955497#L6024c618:952

**Comment by mattmoyer** [comment]
Another instance of this here: https://hush-house.pivotal.io/teams/tanzu-user-auth/pipelines/pinniped-pull-requests/jobs/multiple-pinnipeds-test/builds/121.1#L602c0b7e:830:835

```
        	            	I0216 20:03:59.096381   12118 request.go:1068] Response Body: error trying to reach service: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "Pinniped CA")
        	            	I0216 20:03:59.098631   12118 request.go:1271] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
        	            	I0216 20:03:59.098655   12118 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
        	            	I0216 20:03:59.098689   12118 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: login.concierge.pinniped.dev/v1alpha1: the server is currently unable to handle the request
        	            	F0216 20:03:59.098837   12118 helpers.go:115] error: the server doesn't have a resource type "tokencredentialrequests"

**Comment by mattmoyer** [comment]
More notes in Slack here: https://kubernetes.slack.com/archives/C01BW364RJA/p1613507437328800?thread_ts=1613507346.327300&cid=C01BW364RJA

**Comment by mattmoyer** [comment]
I think this is the same type of flake in `TestKubeClientOwnerRef` ([failed build](https://hush-house.pivotal.io/teams/tanzu-user-auth/pipelines/pinniped-pull-requests/jobs/multiple-pinnipeds-test/builds/121.3#L602c1853:369:374)):
```
    kubeclient_test.go:207: 
        	Error Trace:	kubeclient_test.go:207
        	Error:      	Received unexpected error:
        	            	apiservices.apiregistration.k8s.io "v1.snorlax.dev" not found
        	Test:       	TestKubeClientOwnerRef
--- FAIL: TestKubeClientOwnerRef (2.18s)
```
