### ISSUE TITLE
Tweak impersonation proxy header handling to pass through by default rather than dropping

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#451]
After some discussion, we think it's better to pass through unknown headers rather than dropping them. The theory is that future headers are more likely to attenuate your access rather than increase it. If we drop those headers we are actually _increasing_ the scope of permissions on that request.

On the other hand, if a future header were to broaden your permissions on a request, we might fail in another bad way that made the proxy act as a confused deputy. We decided this is less likely than the first failure type.

The expected behavior is:
- Reject the request if any `Impersonate*` headers are included.
- Pass through all other headers.
- Add our impersonation headers based on the authenticated principal.

cc @enj @cfryanr @margocrawf

**Comment by enj** [comment]
> Pass through all other headers.

We would of course drop the incoming Authorization header and replace it with our own Authorization header for the SA that is doing the impersonation.

**Comment by enj** [comment]
I believe we did this in #355.
