### ISSUE TITLE
Design how multiple IDPs should work in the Supervisor

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#459]
This is a stub to track the initial design work for using multiple IDPs in the Supervisor. For example, it should be possible for a single FederationDomain to be associated with several OIDCIDentityProviders or LDAPIdentityProviders. The code currently assumes a single IDP and refuses to work otherwise.

**Comment by enj** [comment]
Per https://github.com/vmware-tanzu/pinniped/issues/440#issuecomment-786876359

> multiple Domain support - many enterprises don't just have one domain and need to add users from multiple.

This specific LDAP use case would be covered by generic multiple IDP support.

**Comment by mattmoyer** [comment]
Closing as a dupe of https://github.com/vmware-tanzu/pinniped/issues/352.
