### ISSUE TITLE
Concierge impersonation proxy CA certificate should be stored in its own Secret for future-proofing.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#463]
In the initial release of the Concierge impersonation proxy, the serving certificate is signed by a CA key that is immediately discarded (both have 100 year lifetimes). We think in the future we will want to switch to short-lived serving certificates signed by a long-lived CA.

To facilitate this future change, we want to make sure the signing CA is securely stored in a Secret so we can use it for rotation or cross-signing in the future.

**Comment by cfryanr** [comment]
Implemented in https://github.com/vmware-tanzu/pinniped/pull/355/commits/a2ecd052400c42731097459413aeb2d92f08d527 on the impersonation-proxy branch.
