### ISSUE TITLE
Concierge impersonation proxy does not gracefully handle abruptly-disconnected clients.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#464]
In the current implementation, when a client disconnects abruptly (e.g., running `kubectl get -w` and killing the process with Ctrl-C) the server holds open the connection for a long time. Instead, the server should detect that the socket is no longer connected and clean up server resources such as the open port and serving goroutine.

**Comment by cfryanr** [comment]
Steps to reproduce using the latest commit on the `impersonation-proxy` branch (commit sha `2460568` or newer):
```
# In one shell:
./hack/prepare-for-integration-tests.sh -c && ./hack/prepare-impersonator-on-kind.sh
# Wait for the output to say that it is ready.

# Then in a second shell:
stern -n concierge '.*' | grep "servicing request"

# Then in a third shell:
kubectl --kubeconfig /tmp/kubeconfig get ns
kubectl --kubeconfig /tmp/kubeconfig get ns -w
# After a few seconds, control-c to cancel the watch.
```

Back in the stern output, you should see that the original `kubectl get ns` caused two messages to get logged, one saying that it was servicing the request (the `GET /api/v1/namespaces` request) and the other saying that it "finished servicing request". However, for the cancelled watch command the "finished servicing request" is not printed. Wait a few minutes and it will still not be printed.

This seems to indicate that the impersonation proxy server is not closing its connection to the API server for this cancelled request. It might still be running the watch on the Kube API server on behalf of the user, even though the user has disconnected their client.

**Comment by ankeesler** [comment]
Closing this issue as I believe we were misled by our logging. The proxy HTTP handler goroutine and the backend connection resources are indeed cleaned up when the frontend TCP connection is killed.

When the frontend connection to our proxy is closed, the proxy falls through to this `panic()`: https://github.com/golang/go/blob/9de49ae01ad332d8cbb79a3094c3fc3d6b6931e6/src/net/http/httputil/reverseproxy.go#L338. That `panic()` indicates to the Golang `http.Server()` that it should kill the goroutine and connection resources associated with the HTTP handling without printing a stack trace. Therefore, we do not see our log statement about finishing serving the frontend request.

We ensure the printing of this log statement with a `defer`: https://github.com/vmware-tanzu/pinniped/pull/355/commits/aa79bc76098a44b7ca4c004cb251a9106fde2835.

Docs for aforementioned Golang std library entities involved here:
- https://pkg.go.dev/net/http#ErrAbortHandler
- https://pkg.go.dev/net/http#Handler
