### ISSUE TITLE
Write negative integration test cases to verify that "nested" impersonation fails the way we expect

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#465]
In the Concierge impersonation proxy for v0.7.0, we intend to reject incoming requests that attempt to use impersonation. We should write an integration test that verifies that things fail the way we expect.

In the future we intend to add more complex support for some form of "nested" impersonation, but that is out of scope for v0.7.0.

**Comment by cfryanr** [comment]
Added in https://github.com/vmware-tanzu/pinniped/pull/355/commits/41140766f032718fbab8935bd739b4909ee377de
