### ISSUE TITLE
`pinniped get kubeconfig` CLI should keep the name of my cluster

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#513]
### Acceptance Criteria

```gherkin
Given I have a cluster with the Concierge configured
And I have some base admin kubeconfig for my cluster where the name of the cluster is "my-cluster-1"
When I run `pinniped get kubeconfig --generated-name-suffix "-pinniped"`
Then the output cluster name is the same as my original admin kubeconfig suffixed with "-pinniped"
And the name of the new authinfo/user is the same as my original admin kubeconfig suffixed with "-pinniped"
And the name of the new context is the same as my original admin kubeconfig suffixed with "-pinniped"
```

**Is your feature request related to a problem? Please describe.**

When I use `pinniped get kubeconfig` it outputs a new kubeconfig but it loses the name of my context and my cluster, replacing both with the hardcoded string `pinniped`. This shows up later in other tools and UIs. For example, when I then do k9s --kubeconfig <my_new_kubeconfig>` it shows the name of my context and my cluster at the top of the screen.

<img width="1292" alt="k9s Screen Shot" src="https://user-images.githubusercontent.com/25013435/111843327-35a37280-88be-11eb-88fa-33f5c4cc4c9e.png">

**Describe the solution you'd like**

My context and cluster had nice, descriptive names in my kubeconfig at the time that I invoked `pinniped get kubeconfig`. Maybe it should copy those names into the corresponding fields of the kubeconfig that it outputs?

**Describe alternatives you've considered**

No alternatives immediately occurred to me.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**

Unit tests.

- **How does this change the current architecture?**

It doesn't. Just a small detail.

- **How will this change be backwards compatible?**

It would only apply to newly generated kubeconfigs, so no backwards compatibility concern. Users should be be parsing the results of `pinniped get kubeconfig` and depending on the context and cluster names being `pinniped`.

- **How will this feature be documented?**

Not needed.

**Additional context**

None

**Comment by mattmoyer** [comment]
This is a bit open to tweaks, but something like:

```gherkin
Given I have a cluster with the Concierge configured
And I have some base admin kubeconfig for my cluster where the name of the cluster is "my-cluster-1"
When I run `pinniped get kubeconfig`
Then the output cluster name matches my original admin kubeconfig
And the name of the new context is the same as my original admin kubeconfig suffixed with "-pinniped"
```

**Comment by cfryanr** [comment]
@mattmoyer Is there an advantage of adding the "-pinniped" suffix? Like does it make it easier to merge the kubeconfig later or something?

**Comment by mattmoyer** [comment]
The rationale of adding some "-pinniped" suffix is so you can tell whether you have the original admin context or the new Pinniped context selected, for example with https://github.com/jonmosco/kube-ps1.
