### ISSUE TITLE
Impersonation proxy hardening

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#520]
Some things we could do to improve the security posture of the impersonation proxy:

1. Implement proper cross signing CA rotation and start rotating the serving certs "correctly" instead of hard breaking kubeconfigs once a year
2. ~~Use a separate service account with minimal permissions (i.e. impersonate users, groups and extra) when performing the reverse proxy impersonation on the backend~~ https://github.com/vmware-tanzu/pinniped/pull/667
3. ~~Authorize all requests, rather than relying on the kube-apiserver to do authorization~~ https://github.com/vmware-tanzu/pinniped/pull/670
4. Rotate client cert signing key more frequently than one year
5. Always disable anonymous auth
6. Always try to do some dry-run admission control on every request
7. Provision certs via CSR API and use those as creds instead of impersonating the user
8. Dynamically create service accounts with minimal impersonation permissions and use those per request

**Comment by anjaltelang** [comment]
Closing on this as most of the features that need hardening were implemented.
