### ISSUE TITLE
Consider exposing the impersonation proxy generic API server endpoints

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#521]
The generic API server code used by the impersonation proxy creates some endpoints such as `/metrics` which are inaccessible today because we proxy all requests to KAS.  This data could be helpful when running the impersonation proxy in prod under high load.  We could try exposing these endpoints under a custom path `/impersonation-proxy` or on some different port.

Note: the filter latency code surrounding the impersonation proxy handler needs to be updated to track long running requests separately.

**Comment by anjaltelang** [comment]
If there is interest from the community to have this feature, we can re-open the issue.
