### ISSUE TITLE
Pinniped CLI should cache temporary credentials requested by kubectl

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#523]
```gherkin
Scenario log in using cached credentials
Given I have a cluster with the Concierge installed
And I have the Pinniped supervisor installed and configured with some upstream IDP
And I have a kubeconfig YAML from `pinniped get kubeconfig`
When I run `kubectl` and log in
Then I see a cache file created in `~/.config/pinniped/cluster-credentials.yaml` 
And the cache file contains my temporary cluster credentials (certificate)
And when I run `kubectl` again, it is faster
```

### Notes

The cache key for this cache will be something like a SHA-256 hash of the input CLI flags to the `pinniped login [...]` command, as well as any relevant environment variables (such as the variable named by `--static-token-env`).

The cache format should be similar to the existing sessions cache (Kubernetes-style YAML).

We are going to ignore any intermediate credentials for now (ID token, access token, STS ID token), and we are going to base the cache validity only on the lifetime of the ExecCredentialStatus. This change also does not include any asynchronous cache refresh operation (e.g., in a background process or agent).

**Other considerations (implementation details)**
- We also probably don't want this cache to grow indefinitely. 
- think the cache file will be a list of yaml object with some attributes as it exists in our existing code
- should be able to write to the file without corrupting the file 
- some logic around each time processing the file, normalizing it, putting it back in order, removing expired entries  
- could consider using a sqllite db but not sure if we want this...
- could abstract this to key and value types...
- another thing to consider for future proofing: keeping data in a key chain or at least encrypt the entries as this file has credentials in it so we may not want to have these in plaintext

**Comment by enj** [comment]
`PINNIPED_DISABLE_CACHE=1` is a bit misleading because I assume we would still try to use the cached refresh token?

**Comment by mattmoyer** [comment]
Maybe it should also skip that cache?

**Comment by cfryanr** [comment]
Do we need a way to optionally skip the cache? What's the use case for it?

**Comment by enj** [comment]
I was mostly thinking that something like `PINNIPED_DISABLE_TCR_CACHE=1` would be more clear.

**Comment by pabloschuhmacher** [comment]
here is the new acceptance for this story since we are going to remove the skip cache functionality in the original story and have a separate story for log out.

```gherkin
Scenario log in using cached credentials
Given I have a cluster with the Concierge installed
And I have the Pinniped supervisor installed and configured with some upstream IDP
And I have a kubeconfig YAML from `pinniped get kubeconfig`
When I run `kubectl` and log in
Then I see a cache file created in `~/.config/pinniped/cluster-credentials.yaml` 
And the cache file contains my temporary cluster credentials (certificate)
And when I run `kubectl` again, it is faster

```
