### ISSUE TITLE
impersonation proxy: add support for fallback mode

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#550]
We know that Kube environments such as OpenShift fail the heuristic of "if there are control plane nodes, we can exec KCM to borrow the signing key."  While we should add dedicated support for these environments, as a stopgap, we can consider adding a new controller that:

1. Reads the credential issuer
2. If all strategies are failing for more than a minute
3. And the impersonation proxy disabled itself due to the control plane node heuristic
4. Then it would set the impersonation proxy mode to `fallback`
5. If some new strategy comes "online" successfully, the controller would undo the above

The impersonation proxy controller would treat `fallback` to mean the same thing as `enabled` but with a different reason.

**Comment by anjaltelang** [comment]
The Impersonation Proxy can be configured on any Kubernetes cluster. This feature is not needed.
