### ISSUE TITLE
[stub] Design some approach to let admins control the user and groups that Kube sees

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#558]
We have a few use cases to support some kind of mutation of the data from the upstream IDP:

1. Prefixing support (i.e. make multiple IDPs safe to use at the same time)
2. Filtering support of groups (i.e. to prevent sending too many groups to Kube)

**Comment by mattmoyer** [comment]
We might be able to use the same mechanism to do coarse-grained authorization at login time. For example, "only users in a specific group should ever access this cluster".

**Comment by anjaltelang** [comment]
https://github.com/vmware-tanzu/pinniped/issues/352 covers the functionality reported in this issue.
