### ISSUE TITLE
Pinniped documentation (pinniped.dev/docs) should support basic search

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#564]
```gherkin
When I navigate to https://pinniped.dev/docs
Then I see a search box
And when I type a search term into the box
Then I see inline search results
```

We should find a way to add basic search functionality to the website.

Some potential options:

- [docsearch](https://docsearch.algolia.com/): this is what Velero and others use. We'd need to disable our Content-Security Policy due to https://github.com/algolia/instantsearch.js/issues/2868. The security of our docs site isn't the _most_ important thing but it would be good to avoid this if there's another good option.
  
- One of the options mentioned on [the Hugo site](https://gohugo.io/tools/search/). At first glance these all look non-trivial to integrate (especially the search UI part).

**Comment by microwavables** [comment]
@mattmoyer are you saying that you want the ability to type in a word, hit search, and then you're taken to a list of potential articles vs the in-line? ccing @jonasrosland

**Comment by mattmoyer** [comment]
Oh no, I think the inline search is perfect. I was just trying to retroactively write acceptance criteria for what we were looking for here.

This issue should be done. We're just waiting on formal acceptance/validation.

**Comment by microwavables** [comment]
ah! gotcha! all looks good to me
