### ISSUE TITLE
Pinniped documentation website should have restrictive Content-Security-Policy headers.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#567]
We originally enabled these in #447, but had to temporarily roll back that change to add search support in #556.

We want these to mitigate any possible cross-site scripting vulnerabilities on the docs website. The impact of such a vulnerability would be relatively minor but it's still something we want to avoid.

This may be blocked on https://github.com/algolia/instantsearch.js/issues/2868 or finding a different search provider.

**Comment by anjaltelang** [comment]
Closing this bug as we don't see the blocked issue being solved soon.
