### ISSUE TITLE
[stub] Assert the request/response logging of the impersonation proxy is sufficient

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#574]
We do some simple `plog` based logging in the impersonation proxy.  It would be good to manually run the proxy at different log levels and see what information is emitted and if said information is sufficient/correct for the given log level.

Depending on the outcome of above, it may make sense to use the audit logging of the API server code to emit some JSON logs for the request/response.  We would need to be careful about logging request/response bodies.

**Comment by anjaltelang** [comment]
Closing this issue but can be reopened if there is interest.
