### ISSUE TITLE
Enable registering new clients with supervisor

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/pinniped#577]
**Is your feature request related to a problem? Please describe.**

I'm using Pinniped to enable a web app to authenticate requests to the API server and so have created a new client-id in my OAuth2 identity provider. I can't register my new client-id with Pinniped supervisor.

**Describe the solution you'd like**

It should be possible to register my new client-id with supervisor so that it can be used to authenticate with my upstream identity provider.

**Describe alternatives you've considered**

I can currently create a new `JWTAuthenticator` in my workload cluster with my new client-id, so that the workload cluster knows to trust that client-id/IdP, and then use this authenticator instead. This works fine.

**Are you considering submitting a PR for this feature?**

Not right now, no.

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

More details at [Kubeapps on TKG 1.3](https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13-part-2/)

**Comment by enj** [comment]
Lets make sure stuff like #337 is considered when we implement this.

**Comment by anjaltelang** [comment]
Reviewed on 12-7-21. This is on our Roadmap.

**Comment by jamieklassen** [comment]
For my use case specifically, I would like to be able to customize the following fields on a new client at minimum:

* Client ID
* Client Secret
* Redirect URI(s)

Nothing controversial here, just figured I'd spell out the requirements a little more explicitly.

**Comment by cfryanr** [comment]
This was implemented last year but we forgot to close this issue.
