### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by rdimitrov** [vmware-tanzu/pinniped#583]
**What happened?**

Hey, I've noticed the link in the Getting Started section in the README file is broken - https://github.com/vmware-tanzu/pinniped/blame/main/README.md#L46 :) 

**What did you expect to happen?**

I'm okay to raise a quick fix on that, but wanted to check whether you prefer to redirect to the [Tutorials page](https://pinniped.dev/docs/tutorials/), [How-to Guides](https://pinniped.dev/docs/howto/) or somewhere else maybe?

**What is the simplest way to reproduce this behavior?**

Click on README -> Getting started ->  [install and try Pinniped](https://pinniped.dev/docs/demo/) 

**In what environment did you see this bug?**
- Pinniped server version:
- Pinniped client version:
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**

**Comment by mattmoyer** [comment]
Thanks @rdimitrov!
