### ISSUE TITLE
Export `pinniped login oidc` business logic for consumption as library

### ISSUE THREAD

**Issue by ankeesler** [vmware-tanzu/pinniped#585]
**Is your feature request related to a problem? Please describe.**

- I would like to use [the `pinniped login oidc` business logic](https://github.com/vmware-tanzu/pinniped/blob/cc51c72c12b1ff5c188a8318675c16147c1eb4c3/cmd/pinniped/cmd/login_oidc.go#L113-L208) in another CLI.
- My CLI specifically needs the ability to perform the credential exchange(s) to authenticate to a Kubernetes cluster via a `JWTAuthenticator` that is tied to a `FederationDomain`.
- I would like to be able to continually consume improvements (e.g., https://github.com/vmware-tanzu/pinniped/pull/560) and bug fixes (e.g., https://github.com/vmware-tanzu/pinniped/pull/579) that the Pinniped team adds to this code path.
- I don't want to have to rewrite this code myself.

**Describe the solution you'd like**

- Move as much of [the `pinniped login oidc` business logic](https://github.com/vmware-tanzu/pinniped/blob/cc51c72c12b1ff5c188a8318675c16147c1eb4c3/cmd/pinniped/cmd/login_oidc.go#L113-L208) as possible to a public go package in `./pkg`.

**Describe alternatives you've considered**

- We have discussed calling the `pinniped` binary itself from our CLI, but this is a non-starter because of static linking requirements.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- We could have unit tests and integration tests for this package.
- **How does this change the current architecture?**
- Hopefully it doesn't, since we are just making existing code public.
- **How will this change be backwards compatible?**
- It will be backwards compatible because we are adding a net new go package with currently private code.
- **How will this feature be documented?**
- Go package doc?

**Additional context**

**Comment by ankeesler** [comment]
Strawdog package API below. This proposal is less about the actual symbol names and more about the actual package API shape. Another direction we could go here is to offer wrappers around the `pkg/conciergeclient` and `pkg/oidcclient` API (e.g., `func WithConciergeclientOption(opt conciergeclient.Option) Option`, `func WithOidcclientOption(opt oidcclient.Option) Option`). I didn't go this route because it would really tie us to the implementation.

---

```
package login // import "go.pinniped.dev/pkg/login"

Package login provides a Go API to serve as a foundation for a Kubernetes
client-go credential plugin that authenticates to a Kubernetes cluster via a
Pinniped authentication stack (e.g., Supervisor+Concierge, Concierge only).

func OIDC(issuer, clientID string, opts ...Option) error
func Static(token string, opts ...Option) error
type Option func(*loginer) error
    func WithClusterInfo(clusterInfo *clientauthv1beta1.Cluster) Option
    func WithConciergeAPIGroupSuffix(apiGroupSuffix string) Option
    func WithConciergeAuthenticator(teyep, name string) Option
    func WithConciergeCABundleData(caBundleData string) Option
    func WithConciergeEnabled(enabled bool) Option
    func WithConciergeEndpoint(endpoint string) Option
    func WithContext(ctx context.Context) Option
    func WithCredentialCachePath(credentialCachePath string) Option
    func WithDebugSessionCache(debug bool) Option
    func WithOIDCCABundle(caBundle string) Option
    func WithOIDCCABundleData(caBundleData string) Option
    func WithOIDCListenPort(port uint16) Option
    func WithOIDCScopes(scopes []string) Option
    func WithRequestAudience(audience string) Option
    func WithSessionCachePath(sessionCachePath string) Option
    func WithSkipBrowser(skipBrowser bool) Option
    func WithStderr(stderr io.Writer) Option
    func WithStdin(stdin io.Reader) Option
    func WithStdout(stdout io.Writer) Option
```

**Comment by anjaltelang** [comment]
Reviewed on 12-7-21. @ankeesler need your inputs on whether this is still needed.

**Comment by ankeesler** [comment]
@anjaltelang we are still embedding the pinniped CLI in Tanzu[0], and we would still like not to have to embed the pinniped CLI, so yes I would say we still have a desire for this Go API.

[0] https://github.com/vmware-tanzu/tanzu-framework/blob/48b9ff4b8c6d25030df6f4032a6bfbf382e1f00f/cmd/cli/plugin/pinniped-auth/login.go#L45

**Comment by joshuatcasey** [comment]
I believe this is done: https://github.com/vmware-tanzu/pinniped/tree/main/pkg
