### ISSUE TITLE
Support non-interactive password-based LDAP logins (e.g., from CI)

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#636]
```gherkin
Given I have the Concierge and Supervisor installed
And I have an LDAP directory with some service account user and password
And I have configured an LDAPIdentityProvider on the Supervisor
When I generate a kubeconfig using `pinniped get kubeconfig`
And I run `PINNIPED_USERNAME=example-username PINNIPED_PASSWORD=example-password kubectl get ns`
Then the login happens with no username/password prompt and my command succeeds
```

## Notes
We don't generally target "service account" authentication because it's not widely supported on OIDC identity providers, and because Kubernetes has an in-built notion of service accounts that work well for most scenarios. However, a common use case in LDAP-based identity platforms is to want all inter-cluster traffic to be authenticated based on centralized service account identities from the LDAP directory.

This story is meant to support that use case for things like Jenkins or other CI/CD situations, while not changing the default behavior of the `pinniped login` exec credential plugin.

### Open Questions
- Should we pick specific environment variables instead of making them configurable?
- Is there any other mechanism other than environment variables that might be safer way to pass the password? Perhaps a file path?
- How should CLI session caching handle these inputs?

**Comment by shivkumarpatil** [comment]
Hi Mattmoyer sir,

I am started working on Tanzu kubernetes. 
I need to connect the kubernetes cluster from Linux server with PINNIPED_USERNAME and PINNIPED_PASSWD.

I am new to this. Please help me with the configuration. Thank you

My Mail id: shivva45@gmail.com
