### ISSUE TITLE
Add recognizable prefix to Pinniped secrets (auth codes, refresh tokens, access tokens)

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#688]
Something along the lines of https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/. The benefit is if you encounter one of these secrets out of context, it's easy to figure out what you're looking at. We could also add a short checksum as GH did. We probably can't do anything like this for JWT's, but they are somewhat self-describing anyway.

This feature would allow enterprises to reliably scan code repositories for any accidentally-committed tokens.

Notes:
* This is referring to the downstream access & refresh tokens, and authcodes
* Ensure the at_hash claim in the id_token is still correct after this change
* Update the storage version

**Comment by cfryanr** [comment]
One small detail: it would make sense to trim the prefix before using it to create the name of the Kube Secret in which the object (e.g. authcode) is stored. We tried to name these Secrets in such a way that they were not pushing up against the limits of [what it allowed for the length of a Kube resource name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/).

**Comment by anjaltelang** [comment]
Reviewed on 12-7-21. On Roadmap.
