### ISSUE TITLE
Add support for GitHub logins via a GitHubIdentityProvider CRD.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#690]
GitHub supports an OAuth2-based flow, but is not an OIDC provider and does not work with our current APIs.

We should support GitHub as a first-class IDP including group support.

**Comment by anjaltelang** [comment]
Reviewed on 12-7-21. On roadmap.

**Comment by joshuatcasey** [comment]
Done and released in https://github.com/vmware-tanzu/pinniped/releases/tag/v0.31.0
