### ISSUE TITLE
LDAP Result Code 4 "Size Limit Exceeded" during LDAP user search

### ISSUE THREAD

**Issue by pwhetsel** [vmware-tanzu/pinniped#708]
**What happened?**

After standing up Pinniped Supervisor and Concierge and deploying an LDAPIdentityProvider pointed at my LDAP server my LDAPIdentityProvider reports the Ready status:

> 
> ❯ kubectl get ldapidentityproviders.idp.supervisor.pinniped.dev -n pinniped-supervisor
> 
> 
> NAME                   HOST                                STATUS   AGE
> my-ldap-name    my-host:636    Ready    175m

Upon trying to authenticate using the pinniped-cli as my kubectl auth plugin I receive the following error:

> ❯ export KUBECONFIG=my-cluster.yaml
> ❯ kubectl get nodes
> Username: my-username
> Password:
> Error: could not complete Pinniped login: error getting authorization: expected to be redirected, but response status was 502 Bad Gateway

Inspecting the supervisor logs shows that the search results for my user filter is returning more that the maximum number of results on my LDAP server (1000 in my case):

> auth_handler.go:100] "unexpected error during upstream LDAP authentication" warning="true" error="error searching for user: LDAP Result Code 4 \"Size Limit Exceeded\": " upstreamName="my-ldap-idp"

**What did you expect to happen?**

I would expect the user search to page search results the same way that it appears the group search does.

https://github.com/vmware-tanzu/pinniped/blob/49683975abc031d3ff38280d75fb4a56e21f5f0c/internal/upstreamldap/upstreamldap.go#L396

vs

https://github.com/vmware-tanzu/pinniped/blob/49683975abc031d3ff38280d75fb4a56e21f5f0c/internal/upstreamldap/upstreamldap.go#L362

**What is the simplest way to reproduce this behavior?**

Populate an LDAP server with more users that match your user search filter than the default sizelimit parameter of your LDAP server.

**In what environment did you see this bug?**
- Pinniped server version: v0.9.2
- Pinniped client version: v0.9.2
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration: cloud provider managed cluster

**Comment by mattmoyer** [comment]
Thanks for filing the issue!

@cfryanr will be back next week and he may have more context, but I think the rationale for not paging that API call is that (in theory), we've added the specific username to the configured user filter, so that query should return exactly 0 or 1 result.

There's another assertion a bit further down that page that would fail if more than one record matched:
https://github.com/vmware-tanzu/pinniped/blob/49683975abc031d3ff38280d75fb4a56e21f5f0c/internal/upstreamldap/upstreamldap.go#L417-L423

Maybe there's a problem with `spec.userSearch.attributes.username`? That's the API field that controls how the authenticating user's username is used to filter the LDAP user records.

**Comment by pwhetsel** [comment]
Ah! That makes sense. I realize now I lost that pass-through username attribute in my filter when adapting it to my Active Directory server. 

`    filter: "(&(sAMAccountName={})(objectClass=person))"
`
With this filter it works as intended now. Thank you for the quick response.

**Comment by enj** [comment]
Note that you can specify `{}` more than once to allow users to login with different attributes as well:

https://github.com/vmware-tanzu/pinniped/blob/c71703e4db27e243c96db67c2e864d502cb88899/test/integration/ldap_client_test.go#L141-L151
