### ISSUE TITLE
LDAP user filter returning more than one entry should return a proper error message 

### ISSUE THREAD

**Issue by anjaltelang** [vmware-tanzu/pinniped#710]
While using LDAP, if User filter returns more than one entry for a user, the error message needs to describe that more than one entry matched the filter. 
- The validation must make sure that at least {} must be included while filtering. #708 

**In what environment did you see this bug?**
- Pinniped server version: [](url)
- Pinniped client version:
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**

**Comment by cfryanr** [comment]
Hi @anjaltelang,

Is the suggestion that we add a new validation which, upon loading of any LDAPIdentityProvider resource, complains loudly and does not allow the upstream LDAP IDP to be used if the [`spec.userSearch.filter`](https://github.com/vmware-tanzu/pinniped/blob/main/generated/1.20/README.adoc#k8s-api-go-pinniped-dev-generated-1-20-apis-supervisor-idp-v1alpha1-ldapidentityproviderusersearch) does not contain any '{}' in the string (when a non-empty string was provided)?

We could consider the same validation for the LDAPIdentityProvider's [`spec.groupSearch.filter`](https://github.com/vmware-tanzu/pinniped/blob/main/generated/1.20/README.adoc#k8s-api-go-pinniped-dev-generated-1-20-apis-supervisor-idp-v1alpha1-ldapidentityprovidergroupsearch).

Validation errors could be written to the LDAPIdentityProvider's `status`.

**Comment by mattmoyer** [comment]
Closing in favor of https://github.com/vmware-tanzu/pinniped/issues/736
