### ISSUE TITLE
Docs for previous versions of Pinniped

### ISSUE THREAD

**Issue by margocrawf** [vmware-tanzu/pinniped#735]
Currently, our docs site only shows the latest version of main.

If you want to look at docs for a previous release, there is no way to see them.
By default we should show the docs for the latest release, with a dropdown menu to view snapshots of what the docs looked like when previous releases were tagged.

**Comment by anjaltelang** [comment]
Reviewed on 12-7-21. This maybe useful for future versioning work.

**Comment by shamus** [comment]
Closing this for now, as we're pre 1.0 and the benefit of maintaining these docs is likely outweighed by the cost.

We should definitely reconsider this suggestion post 1.0.
