### ISSUE TITLE
Fix small timeouts causing flakes

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#802]
ex: https://hush-house.pivotal.io/teams/tanzu-user-auth/pipelines/pinniped-pull-requests/jobs/integration-test-gke-1.18/builds/527#L6114f1f2:1160

https://kubernetes.slack.com/archives/C01BW364RJA/p1629502705155100?thread_ts=1629499452.153400&cid=C01BW364RJA

**Comment by cfryanr** [comment]
Not seeing these flakes anymore.
