### ISSUE TITLE
Is there any UI access provisioned?

### ISSUE THREAD

**Issue by sburnwal** [vmware-tanzu/pinniped#882]
Pinniped team, I played around the project and was able to setup pinniped supervisor and concierge. Using CLI, I can access different clusters via Supervisor as OIDC token provider. 

I have a question - is there any UI access also available and if yes, then how? How do I use the Supervisor OIDC provider to login to different clusters using browser (without using any CLI) so that I can access say Kubernetes dashboard and other resources etc using a browser?

**Comment by enj** [comment]
There is currently no support for dashboards and related UIs unless the dashboard itself supports pinniped under the hood.  For example, [kubeapps](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider-with-pinniped.md) has direct support for pinniped.

#577 would be needed for custom OAuth client support to allow registering clients for dashboards and something like #337 is needed to support LDAP IDPs in the browser (because they have no UI).

Furthermore, something like kubeapp's [pinniped-proxy](https://github.com/kubeapps/kubeapps/blob/master/docs/developer/pinniped-proxy.md) is required if want access to the Kubernetes API in environments like GKE where the pinniped concierge is a strict requirement to wire in our custom authentication layer.  If you have full control of the API server and can set the OIDC flags, then this can be skipped.

**Comment by sburnwal** [comment]
Thanks and have a follow up. I assume Pinniped CLI is acting as an OIDC client and it would be using REST calls to the Supervisor to get the OIDC token. If I deploy my custom UI app as an OIDC client using the same clientId as used by Pinniped CLI, can I not do UI based login? For now I am interested in getting Supervisor token only, not the token for managed cluster.

**Comment by enj** [comment]
> If I deploy my custom UI app as an OIDC client using the same clientId as used by Pinniped CLI, can I not do UI based login?

That client ID only supports a redirect URI set to `127.0.0.1`.  This makes it usable with web UIs.

**Comment by sburnwal** [comment]
OK, understood. One more thing - the token that I see in file **~/.config/pinniped/sessions.yaml** under the element **sessions.tokens.id.token**, it appears to have **aud = pinniped_cli**. So in my understanding this is the common token from the supervisor and would be used to generate cluster specific token later when I access a specific workload cluster. Is there a way to see or log what cluster specific token is being generated once the CLI would request the supervisor for cluster specific token?

**Comment by enj** [comment]
> So in my understanding this is the common token from the supervisor and would be used to generate cluster specific token later when I access a specific workload cluster.

No, `sessions[].tokens.access.token` is used in the RFC8693 token exchange.

https://github.com/vmware-tanzu/pinniped/blob/f03e5f4fefb5fceb517db9defbcd28da7a44110f/internal/oidc/token_exchange.go#L64-L65

> Is there a way to see or log what cluster specific token is being generated once the CLI would request the supervisor for cluster specific token?

There is not.

**Comment by sburnwal** [comment]
> No, `sessions[].tokens.access.token` is used in the RFC8693 token exchange.

Yes I meant that only, I mean `sessions[].tokens.access.token` is a supervisor issued token for CLI which is used to get cluster specific token using RFC8693 token exchange later.

One more thing - Cluster specific token makes sure that a token is used for accessing a specific token. Is there any way to enforce such behavior at the user level? For example, a user1 may have access to say 2 out 10 managed clusters while user2 may have access to another set of clusters? Is there a way to enforce certain users have access to certain clusters only?

**Comment by enj** [comment]
> I mean `sessions[].tokens.access.token` is a supervisor issued token for CLI which is used to get cluster specific token using RFC8693 token exchange later.

Correct.

> Is there any way to enforce such behavior at the user level? For example, a user1 may have access to say 2 out of 10 managed clusters while user2 may have access to another set of 3 different clusters? Is there a way to enforce that certain users have access to certain clusters only?

Not today.  We have considered having some form of policy enforcement as part of #352.  We have also considered giving the supervisor a stronger concept of a cluster so it can help generate kubeconfigs #751.  Once we have the policy enforcement and the cluster concept, we could build such a compatibility (i.e. during the token exchange, the supervisor would check if the policy allowed the user to exchange their token for the cluster's audience).  Today, there is no enforcement on what audience a user can request, thus they are able to ask for anything.  Over time, we hope to provide the ability to lock this down (and likely will have it locked down more by default).  At the earliest, these are 2022 items.

---

BTW, we have our community meeting today at [9 AM PT / 12 PM ET](https://github.com/vmware-tanzu/pinniped#community-meetings) via [zoom](https://vmware.zoom.us/j/93798188973?pwd=T3pIMWxReEQvcWljNm1admRoZTFSZz09).  Feel free to join and ask any further questions you may have.

**Comment by sburnwal** [comment]
Thank you for responding. About Kubeapps for GUI access, I have not dived yet into how Kubeapps works. When we do Kubeapps integration with Pinniped, how does that work if Pinniped does not allow more than one client which is reserved for the CLI? If Kubeapps works talks to Concierge, that would mean it gets a short lived cert but then browser would need a token right (and not a cert)?

**Comment by enj** [comment]
> When we do Kubeapps integration with Pinniped, how does that work if Pinniped does not allow more than one client which is reserved for the CLI?

Kubeapps only uses the concierge; it does not use the supervisor at all.  Thus Kubeapps registers its own OIDC issuer as a `JWTAuthenticator`.  It then issues its own ID tokens to browser based clients.  When such an ID token is presented to Kubeapps, it proxies the connection back to the API server, and transparently exchanges the ID token for a client certificate in the backend.  The user only sees the ID token, and is unaware of the concierge, client cert, proxy, etc.

**Comment by sburnwal** [comment]
> When such an ID token is presented to Kubeapps, it proxies the connection back to the API server, and transparently exchanges the ID token for a client certificate in the backend.

Thanks @enj, you have been diligently answering my question. Closing the issue!
