### ISSUE TITLE
TLS follow-up: write and implement TLS config KEP for client-go

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#900]
Follow-up from #820

This KEP is for 1.25, deadlines for 1.25 KEPs are within the month of April.

client-go lacks the knobs needed to control the TLS min version and cipher suites.  Our existing code hacks around this limitation:

https://github.com/vmware-tanzu/pinniped/blob/cd686ffdf31ae2a5f7241cd8d3ddf304c0684a19/internal/kubeclient/kubeclient.go#L125-L182

However, this is not a perfect solution because many other clients exist inside the Kube code we use, and there is generally no good way to "fix" them.  We should fix this upstream by allowing the global default to be changed along with support for per `rest.Config` overrides.

- [x] Discuss with SIG API Machinery -> https://youtu.be/FthT95lwMM8?t=1050
- [x] Discuss with SIG Auth -> https://youtu.be/BG_LbZOPfxg?t=535
- [ ] Write KEP (David Eads is interested in reviewing a KEP for this)
- [ ] Implement KEP

High level summary from the discussions linked above (watching the recordings is recommended):

- TLS configuration should allow cipher control for TLS 1.2 and it should allow TLS 1.3 to be used (no cipher control).
- There should be the ability to configure the default globally per process in client-go
- a `rest.Config` should be able to explicitly override the default
- Does _not_ need to flow all the way through to the kubeconfig schema or `kubectl` flags

**Comment by shamus** [comment]
@enj this is describing upstream work in K8s.  I don't think an issue in Pinniped is the best way to track this effort.
