### ISSUE TITLE
Update k8s.io/apiserver to use newer go.opentelemetry.io/otel/semconv dep so we can bump github.com/ory/x

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#916]
From #914

> Only bump github.com/ory/x to v0.0.297 instead of the latest v0.0.321 because v0.0.298+ pulls in a newer version of go.opentelemetry.io/otel/semconv which breaks k8s.io/apiserver.  We should update k8s.io/apiserver to use the newer code.

We are currently stuck on `github.com/ory/x` `v0.0.297` until we fix this (we can probably use a `replace` directive in a pinch but that would likely be a temporary fix).

**Comment by joshuatcasey** [comment]
The version numbers referenced here are pretty stale, and `go.opentelemetry.io/otel/semconv` does not appear to be used by Pinniped at this time.
