### ISSUE TITLE
Generate open API schema for concierge APIs to reduce log noise

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#936]
The lack of open API schema support for the concierge aggregated APIs results in the following scary log messages in the API server logs:

```
E1229 15:34:45.928937       1 controller.go:116] loading OpenAPI spec for "v1alpha1.login.concierge.pinniped.dev" failed with: OpenAPI spec does not exist
I1229 15:34:45.928949       1 controller.go:129] OpenAPI AggregationController: action for item v1alpha1.login.concierge.pinniped.dev: Rate Limited Requeue.
```

These are benign and can be ignored.  The only thing that does not work is `kubectl explain` for these aggregated APIs:

```
kubectl explain tokencredentialrequests
error: couldn't find resource for "login.concierge.pinniped.dev/v1alpha1, Kind=TokenCredentialRequest"
```

To make these errors go away, we should restore the `generated/latest/client/concierge/openapi/zz_generated.openapi.go` codegen from #631 and wire it into https://github.com/vmware-tanzu/pinniped/blob/cc88d2a334e43fb1c10215dad018d007e671aa4e/internal/concierge/server/server.go#L224

Example of how to do this: [1](https://github.com/openshift/openshift-apiserver/blob/d1579827f73b69d28f3144242e3c38e3fcc14701/pkg/cmd/openshift-apiserver/openshiftapiserver/config.go#L98) [2](https://github.com/openshift/openshift-apiserver/blob/d1579827f73b69d28f3144242e3c38e3fcc14701/pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/openapi.go#L33)

It should be easy to write an integration test that asserts that `kubectl explain` works for all pinniped APIs, similar to https://github.com/vmware-tanzu/pinniped/blob/cc88d2a334e43fb1c10215dad018d007e671aa4e/test/integration/kube_api_discovery_test.go#L306

**Comment by cfryanr** [comment]
This work will be done in the dynamic_clients feature branch, so it will be released along with the dynamic clients feature.
