### ISSUE TITLE
Ldap integration for vsphere with tanzu enabled.

### ISSUE THREAD

**Issue by ravvalika** [vmware-tanzu/pinniped#949]
we are trying to integrate tanzu kubernetes cluster with ldap integration.
we have vsphere with tanzu enabled in the vcenter server .
We will be creating tanzu kubernetes cluster from the workload management in the vcenter.
How we can integrate our tanzu kubernetes cluster with ldap in vsphere with tanzu enabled?

**Comment by enj** [comment]
Please reach out through official support channels for questions regarding commerical offerings with Pinniped integration.
