### ISSUE TITLE
Ldap integration for vsphere when tanzu is enabled

### ISSUE THREAD

**Issue by amitpwc** [vmware-tanzu/pinniped#950]
we are trying to integrate tanzu kubernetes cluster with ldap integration.
we have vsphere with tanzu enabled in the vcenter server .
We will be creating tanzu kubernetes cluster from the workload management in the vcenter.
How we can integrate our tanzu kubernetes cluster with ldap in vsphere with tanzu enabled?

**Comment by enj** [comment]
https://github.com/vmware-tanzu/pinniped/issues/949#issuecomment-1014826334
