### ISSUE TITLE
Support configuring different OIDC IDPs in Supervisor that users can authenticate with to access same Kubernetes cluster

### ISSUE THREAD

**Issue by anjaltelang** [vmware-tanzu/pinniped#961]
Support configuring OIDC IDPs differently for different types of users. Need to allow multiple OIDCIdentityProviders. For example, two-factor auth is required for admins but not for deployment service accounts in which case you may have one client that requires OIDC Password grant flows and another that does not. Also, there maybe a use case where one set of clusters would like to have Password grant support and another set without password grant support. 
 
**Is your feature request related to a problem? Please describe.**Yes. See above. This is a use case of Multiple IDP Support in the Supervisor. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by enj** [comment]
> For example, two-factor auth is required for admins but not for deployment service accounts in which case you may have one client that requires OIDC Password grant flows and another that does not.

These types of policies are generally enforced at the IDP itself.  I do not consider this a valid use case for us to worry about.

> Also, there maybe a use case where one set of clusters would like to have Password grant support and another set without password grant support.

Password grant support is generally complex and depends on one or more of: IDP config, IDP OAuth client config, user config, and pinniped config.  This is unlikely to be as cut as dry as "one set of clusters."  What we have today is sufficient IMO - enable password grant support in pinniped and let the IDP decide if it will honor it for the current user.

**Comment by anjaltelang** [comment]
> > For example, two-factor auth is required for admins but not for deployment service accounts in which case you may have one client that requires OIDC Password grant flows and another that does not.
> 
> These types of policies are generally enforced at the IDP itself. I do not consider this a valid use case for us to worry about.
> 
> > Also, there maybe a use case where one set of clusters would like to have Password grant support and another set without password grant support.
> 
> Password grant support is generally complex and depends on one or more of: IDP config, IDP OAuth client config, user config, and pinniped config. This is unlikely to be as cut as dry as "one set of clusters." What we have today is sufficient IMO - enable password grant support in pinniped and let the IDP decide if it will honor it for the current user.

**Comment by anjaltelang** [comment]
enable password grant support in pinniped and let the IDP decide if it will honor it for the current user.
I would say this is still a valid use case because configuring clusters to support access with both password grant and non-password grant flows is an Admin decision. Having this as a configuration option might be useful to the Cluster Admin. Ofcourse, There is always workarounds that can be in place such as having AuthZ rules and policies to handle this, but we should explore this further, if not for MVP.

**Comment by anjaltelang** [comment]
Closing this issue as this is a Dup of https://github.com/vmware-tanzu/pinniped/issues/960
