### ISSUE TITLE
Support Configuring Multiple LDAP clients for different users

### ISSUE THREAD

**Issue by anjaltelang** [vmware-tanzu/pinniped#962]
Support configuring LDAP clients differently for human users vs service accounts that are part of different branches of the LDAP tree/ AD forest. When using AD or LDAP as your upstream IDP, each LDAPIdentityProvider or ActiveDirectoryIdentityProvider can only have one user search base. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by enj** [comment]
This seems unrelated to multiple IDPs and instead looks like it would be better served by an enhancement to the AD/LDAP IDPs themselves by allowing the specification of more than one user/group search base (i.e. do not make the admin repeat a bunch of config).

**Comment by anjaltelang** [comment]
It could be that this is not necessary as a separate story and can be pooled in with https://github.com/vmware-tanzu/pinniped/issues/960,  but it is a use case of Multiple IDP where your Admin needs to configure different LDAP clients for Service Accounts and Human users.

**Comment by enj** [comment]
> Admin needs to configure different LDAP clients for Service Accounts and Human users

Except that they do not need to do that.  If we supported multiple search bases, you could have a single IDP config that let you properly express that intent easily and without duplication of config.

**Comment by anjaltelang** [comment]
https://github.com/vmware-tanzu/pinniped/issues/960
