### ISSUE TITLE
Support Configuring Supervisor with IDPs from Different Organizations

### ISSUE THREAD

**Issue by anjaltelang** [vmware-tanzu/pinniped#963]
Multiple IDP Usecase where you can configure the Pinniped Supervisor to allow users from two different Organizations to access same cluster. For example, if one organization acquires another, then Users from both the original org and the newly acquired/merged org  should be able to access the clusters using their Identity Providers. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by enj** [comment]
This story needs to be expanded with what the expectations are around the isolation of identities (if any) from these different sources.

**Comment by anjaltelang** [comment]
Expectation is that we handle: Isolation/tenancy would be per IDP.  If incase you have a User that belongs to both the new org as well as old org, they should be able to login to the cluster with either of their credentials

**Comment by enj** [comment]
> Expectation is that we handle: Isolation/tenancy would be per IDP. If incase you have a User that belongs to both the new org as well as old org, they should be able to login to the cluster with either of their credentials

It is not that simple - what user does Kubernetes see at the end?  i.e. what authorization policies apply?

**Comment by anjaltelang** [comment]
Closing this issue as it is a DUP of https://github.com/vmware-tanzu/pinniped/issues/960
