### ISSUE TITLE
go install does not work due to use of replace directives

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#972]
```shell
go install -v go.pinniped.dev/cmd/pinniped@latest
```

```
go: downloading go.pinniped.dev v0.13.0
go install: go.pinniped.dev/cmd/pinniped@latest (in go.pinniped.dev@v0.13.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

This started [failing](https://hush-house.pivotal.io/teams/tanzu-user-auth/pipelines/pinniped-go-compatibility/jobs/go-install-cli/builds/114) with the `v0.13.0` release.

Ideally this _should_ work.

**Comment by joshuatcasey** [comment]
At this time we're forced to use `replace` directives in the `go.mod` since we want to use the latest `k8s.io` libraries which almost always have stale dependencies.
