### ISSUE TITLE
Documentation for configuring Pinniped Supervisor with Auth0 as an OIDC IDP 

### ISSUE THREAD

**Issue by anjaltelang** [vmware-tanzu/pinniped#984]
Auth0 is an Identity provider that uses OpenID Connec and OAuth 2.0 to authenticate users and verify their identity. See details [here](https://auth0.com)

This feature request is for adding documentation on how to configure Pinniped Supervisor so that users can authenticate to their Kubernetes cluster using Auth0 credentials. The documentation should go under Pinniped [How-to guides](https://pinniped.dev/docs/howto/). 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by junoriosity** [comment]
Also to me it would be very beneficial.

**Comment by joshuatcasey** [comment]
I'll pick this up!
